Add options `regex` and `ignore` to rule `macro_names`
inaka/elvis_core pull request #131
Opened 2020-09-09 23:39 UTC by paulo-ferraz-oliveira

2020-09-09 23:46 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +    {ok, Regex} = re:compile("^ *[-]define *[(] *([']([^']*)[']|[^,( ]+)"),
I found this regexp to not cover stuff like `-define('A,a', 2).` which, although ugly, might show up in the wild.

Let me know if this change is OK. My goal here is to try and fetch:
1. either `'Macro'` (' followed by a potential repetition of non-' followed by '),
2. or `Macro` (a potential repetition of non ", or (" chars.

2020-09-09 23:47 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +    case re:run(Line, Regex, [{capture, [1], list}]) of
Added this because of the group that's created in the new match.

2020-09-09 23:47 UTC, paulo-ferraz-oliveira commented on test/style_SUITE.erl
> +    [_] = elvis_style:macro_names(ElvisConfig, Path, #{ regex => "^[A-Za-z_ ]+$" }),
Which a regex stuff that was failing (at least 1) is not failing any more.

2020-09-09 23:48 UTC, paulo-ferraz-oliveira commented on test/style_SUITE.erl
> +    [] = elvis_style:macro_names(ElvisConfig, Path, #{ regex => "^[A-Za-z_ \-]+$" }),
With an "improved" regexp nothing fails.

2020-09-09 23:48 UTC, paulo-ferraz-oliveira commented on test/style_SUITE.erl
> +    [_, _, _, _, _] = elvis_style:macro_names(ElvisConfig, Path, #{ regex => "^POTENTIAL_BAD-NAME$" }).
With a very targeted regexp almost everything fails.

2020-09-09 23:49 UTC, paulo-ferraz-oliveira commented
Let me know if I should add more tests or make them more readable.

Actually, now that I think about it I didn't add a test for `ignore`. I'ma do it.

2020-09-09 23:50 UTC, paulo-ferraz-oliveira commented
> Let me know if I should add more tests or make them more readable.
> 
> Actually, now that I think about it I didn't add a test for `ignore`. I'ma do it.

There you go: 6057b99.

2020-09-09 23:58 UTC, paulo-ferraz-oliveira commented
Added a new regression test for https://github.com/inaka/elvis/issues/515#issuecomment-689870216.

2020-09-10 07:33 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    {ok, Regex} = re:compile("^ *[-]define *[(] *([']([^']*)[']|[^,( ]+)"),
This is very much *intentional*. We do want to emit a warning if people use `A,a` as a macro name. That's the whole point :)

2020-09-10 07:35 UTC, elbrujohalcon requested changes

2020-09-10 07:35 UTC, elbrujohalcon commented on test/examples/fail_macro_names.erl
> +-define('A,aZ', 2).
These 2 should definitely be rejected by the rule (at least, with default configuration).

2020-09-10 07:37 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    {ok, Regex} = re:compile("^ *[-]define *[(] *([']([^']*)[']|[^,( ]+)"),
In other words: Make the default regex as strict as possible.

2020-09-10 07:43 UTC, elbrujohalcon approved these changes

2020-09-10 07:43 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    {ok, Regex} = re:compile("^ *[-]define *[(] *([']([^']*)[']|[^,( ]+)"),
Yeah… probably, _the right solution:tm:_ …      would be to actually use the AST for this instead of parsing the code manually as a string.
In any case, this change is fine until that day…

2020-09-10 07:45 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    Regex = maps:find(regex, RuleConfig),
What if we just use a default regex, like `[A-Z][A-Z_0-9]+`?

2020-09-10 10:28 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +    {ok, Regex} = re:compile("^ *[-]define *[(] *([']([^']*)[']|[^,( ]+)"),
I've never used the AST, but could try to check it out.

2020-09-10 10:29 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +    Regex = maps:find(regex, RuleConfig),
That would break those cases where `to_upper` was valid (e.g. 'A-Z', even if ugly), but if it's something you prefer we can go with that.

2020-09-10 10:39 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    Regex = maps:find(regex, RuleConfig),
Yeah, that was the original intention anyway. Let's break ugly macro names! 💣

2020-09-10 10:43 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    {ok, Regex} = re:compile("^ *[-]define *[(] *([']([^']*)[']|[^,( ]+)"),
There are several other rules using it, like the one for atoms you created in the other PR ;)

2020-09-10 20:04 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +    {ok, Regex} = re:compile("^ *[-]define *[(] *([']([^']*)[']|[^,( ]+)"),
Oh, you mean that `katana` stuff.

2020-09-10 20:25 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +    Regex = maps:find(regex, RuleConfig),
Done in eca94aa.

2020-09-10 20:26 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> --define(INVALID_MACRO_NAME_MSG,
This no longer makes sense, since we now have a regexp-based approach.

2020-09-10 20:27 UTC, paulo-ferraz-oliveira commented on test/style_SUITE.erl
> +    [_, _, _, _] = elvis_style:macro_names(ElvisConfig, Path, #{}),
A new one started to fail, since now were not simply considering `to_upper`.

2020-09-10 21:29 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +    {ok, Regex} = re:compile("^ *[-]define *[(] *([']([^']*)[']|[^,( ]+)"),
Done in 73f125c. I'll open a new discussion there, since there are details I'm not comfortable with.

2020-09-10 21:30 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +    case ktn_code:type(MaybeMacro) of
Isn't there a better way to do this? I looked at what `katana` produced and basically got stuff from there, but I feel there's a better way.

2020-09-10 21:33 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +        = case lists:keyfind(_KeyVar = var, _N = 1, MacroNodeValue) of
Also here, I feel there must be a better way to do this. Initially, I targeted type `macro` but that actually shows up when a macro is used, not defined, which is what we're interested in.

I later used `'ATOM'` in the macro definition, which provoked an error, since
```erlang
-define(MACRO, 2).
```
produces different `katana` structures from
```erlang
-define('MACRO', 2).
```
(first one is a `var`, second one is an `atom`).

Also, I didn't want to deep-dive into `katana`, nor could I find up-to-date information on the API.

2020-09-10 21:34 UTC, paulo-ferraz-oliveira commented
Anyway, this is working (ups, tests are failing), and I'll want to `elvis` `elvis_core` since there's some stuff needing fixes there, too.

2020-09-10 22:05 UTC, paulo-ferraz-oliveira commented on elvis.config
> +                  {elvis_style, no_debug_call, #{ignore => [elvis_result, elvis_utils]}}],
Not too sure about this one, but there be `io:format` inside.

2020-09-10 22:06 UTC, paulo-ferraz-oliveira commented
> I'll want to elvis-lint elvis_core

d50fbb2

2020-09-11 09:26 UTC, elbrujohalcon approved these changes
I think this is good to go.

2020-09-11 09:26 UTC, elbrujohalcon commented on elvis.config
> +                  {elvis_style, no_debug_call, #{ignore => [elvis_result, elvis_utils]}}],
Yeah, `elvis` is a CLI… it *has* to have `io:format` somewhere.

2020-09-11 09:26 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    case ktn_code:type(MaybeMacro) of
I think this is _the right way_:tm:.
Macros are very hard to parse. I learned that while implementing the formatter 🤦

2020-09-11 09:26 UTC, elbrujohalcon commented on src/elvis_style.erl
> +        = case lists:keyfind(_KeyVar = var, _N = 1, MacroNodeValue) of
It's very very ugly… but I think this is the only way.
The alternative would be to use `ktn_dodger`, as we do in the formatter, but that comes with another huge pile of nightmares.

2020-09-11 09:27 UTC, elbrujohalcon commented
@paulo-ferraz-oliveira once you fix the tests, let me know and I can merge this.

2020-09-11 13:41 UTC, paulo-ferraz-oliveira commented on elvis.config
> +                  {elvis_style, no_debug_call, #{ignore => [elvis_result, elvis_utils]}}],
If only there were an `allow_debug_call` :D to which we would add non-ignored functions :D

2020-09-11 13:43 UTC, paulo-ferraz-oliveira commented
What about the fact that `katana-code`'s `-spec(_).` is incomplete/wrong. Should we care about that (in the context of another repo, ofc)?

2020-09-11 14:05 UTC, paulo-ferraz-oliveira commented
> @paulo-ferraz-oliveira once you fix the tests, let me know and I can merge this.

Pushed c414b1f. I don't exactly know what `katana-code`'s main goals are, but the new addition of code (about getting a macro's name) could well live inside it, right? ... since we're messing, in `elvis_core`'s context with `katana-code`'s internal structures.

2020-09-11 14:08 UTC, elbrujohalcon commented
@jfacorro ☝️That's your territory :P

2020-09-12 18:50 UTC, merged

2020-09-13 06:55 UTC, jfacorro commented on src/elvis_style.erl
> +check_macro_names(_Regexp, [] = _MacroNodes, ResultsIn) ->
Why the removal of the spec? 😄

2020-09-13 06:57 UTC, jfacorro commented
> I don't exactly know what katana-code's main goals are, but the new addition of code (about getting a macro's name) could well live inside it, right? ... since we're messing, in elvis_core's context with katana-code's internal structures.

I couldn't find in this PR's code where we are manipulating internal katana-code data structures. As far as I could see we are using `ktn_code:attr/2` for getting values.

2020-09-13 10:48 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +check_macro_names(_Regexp, [] = _MacroNodes, ResultsIn) ->
You're right, this shouldn't have happened. Since I rewrote the function I accidentally took it out. In my lib.s I'm usually as strict as `missing_spec_all`. Shall I re-add it?

2020-09-13 10:55 UTC, paulo-ferraz-oliveira commented
> > I don't exactly know what katana-code's main goals are, but the new addition of code (about getting a macro's name) could well live inside it, right? ... since we're messing, in elvis_core's context with katana-code's internal structures.
> 
> I couldn't find in this PR's code where we are manipulating internal katana-code data structures. As far as I could see we are using `ktn_code:attr/2` for getting values.

What I meant was "I'm handling a `katana-code` generated structure that can eventually change (https://github.com/inaka/elvis_core/pull/131/files#diff-9d4ce82551a31e44e1d37fb5c5966363R913) (and the code that does it, in the scope of `elvis` might surely be incomplete), especially since its `spec` specifies the return as `term()`..." 😄. I had proposed that this code be moved to `katana-code` since knowing about the internals shouldn't be required at this level, I guess. (I usually prefer opaque data structures that I "query" the producer for information about). No biggie, if we want it elsewhere, at least in the context of `elvis` it's now a function by itself.