Add new `rule atom_naming_convention`
inaka/elvis_core pull request #132
Opened 2020-09-10 02:55 UTC by paulo-ferraz-oliveira

2020-09-10 02:57 UTC, paulo-ferraz-oliveira commented
Implementation should probably be tested in a few different projects before we can accept the default `regex`.

2020-09-10 03:15 UTC, paulo-ferraz-oliveira commented on src/elvis_rulesets.erl
> +  , {elvis_style, atom_naming_convention, #{regex => "^([a-z][a-z0-9_]+)$", ignore => []}}
I'm unsure about the default value. It works OK for most of the stuff I tested, but e.g. it doesn't when we call a `_SUITE` module (which is OK for rule `module_naming_convention`'s default).

2020-09-10 03:16 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +            AtomNodes = elvis_code:find(fun is_atom_node/1, Root, #{traverse => all, mode => node}),
I'm unsure about the `mode`. I think I tested with zipper and it worked OK too.

2020-09-10 03:17 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +    AtomName = string:strip(AtomName0, both, $'),
I do this so that we may analyze the name itself (considering an atom with `'`) but it might be misleading regarding the regex we include in the config., which will not require `'`. Well, we _are_ talking about the "name".

2020-09-10 03:17 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +                  Info = [AtomName0, Line, Regex],
... though I still print it has found in the code.

2020-09-10 07:31 UTC, elbrujohalcon requested changes

2020-09-10 07:31 UTC, elbrujohalcon commented on src/elvis_rulesets.erl
> +  , {elvis_style, atom_naming_convention, #{regex => "^([a-z][a-z0-9_]+)$", ignore => []}}
🤔  The original idea was to prevent stuff in `camelCase`… so I would just add `(_SUITE)?` to this default, just in case, and be done with it.

2020-09-10 07:31 UTC, elbrujohalcon commented on src/elvis_rulesets.erl
> +  , {elvis_style, atom_naming_convention, #{regex => "^([a-z][a-z0-9_]+)$", ignore => []}}
We can always adjust the default later if people complain about it too much.

2020-09-10 07:31 UTC, elbrujohalcon commented on src/elvis_style.erl
> +            AtomNodes = elvis_code:find(fun is_atom_node/1, Root, #{traverse => all, mode => node}),
I'm unsure as well, but if it works… it's probably fine.

2020-09-10 07:31 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    AtomName = string:strip(AtomName0, both, $'),
I would've done the same… or maybe even ignore atoms that are enclosed in `'` altogether, considering that if you _had_ to use apostrophes, then your atom is not "normal" and should probably not be checked with the regex.

Maybe you can add a configuration option, like `enclosed_atoms => regex()`, that defaults to `.*`.
Or (without that parameter), check the whole thing with the regex, but add something like `|('.*')` to the default regex so that it immediately skips all enclosed atoms.

I personally favor the addition of `enclosed_atoms => same | regex()`, so that the user can specify that they want to use the same regex for all atoms regardless of enclosing. Not sure why someone would want that, instead of just removing the `'`s, but… 🤷

2020-09-10 07:31 UTC, elbrujohalcon commented on src/elvis_style.erl
> +                  Info = [AtomName0, Line, Regex],
This is the right thing to do

2020-09-10 10:35 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +            AtomNodes = elvis_code:find(fun is_atom_node/1, Root, #{traverse => all, mode => node}),
Do you think it would be best to find somebody that was not unsure (i.e. "sure") :-) and teach us both something?

2020-09-10 10:40 UTC, elbrujohalcon commented on src/elvis_style.erl
> +            AtomNodes = elvis_code:find(fun is_atom_node/1, Root, #{traverse => all, mode => node}),
I was actually waiting for @jfacorro to comment… but it's likely that he'll just say "it's fine as it is, folks!"

2020-09-11 00:01 UTC, paulo-ferraz-oliveira commented on src/elvis_rulesets.erl
> +  , {elvis_style, atom_naming_convention, #{regex => "^([a-z][a-z0-9_]+)$", ignore => []}}
Done: 0f1a7f7

2020-09-11 00:32 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +    AtomName = string:strip(AtomName0, both, $'),
This should do it: 56eb5f8.

2020-09-11 09:55 UTC, elbrujohalcon requested changes

2020-09-11 09:55 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    IsEnclosed = is_enclosed_atom(AtomName0, AtomName),
Does this work with `'\' this nasty atom\''`?
Maybe a more naïve, but still reasonable approach would be…

```erlang
IsEnclosed = AtomName0 =/= AtomName
```

…or maybe instead of `string:strip/3` you should use plain ol' pattern-matching… `[$'|RestOfTheAtomName]`…

2020-09-11 09:58 UTC, elbrujohalcon commented on test/examples/fail_atom_naming_convention.erl
> +    'and_neither-is_this',
Please add a few atoms with backticks in them (i.e. `'\'', '\'\'', '\'startswithbacktick', 'backtick\'inside', 'backtick at the end\''`).

2020-09-11 11:52 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +    IsEnclosed = is_enclosed_atom(AtomName0, AtomName),
> Does this work with `'\' this nasty atom\''`?

I can look closer into it (and add it to the tests). I don't see why it shouldn't. As long as `katana-code` is returning the atom as "\' this nasty atom\'", the comparison shouldn't fail.

2020-09-11 12:24 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +    IsEnclosed = is_enclosed_atom(AtomName0, AtomName),
Well, yeah, I've found an issue with the strip'ing. I'm going to use `string:replace` instead. I also found that the error message would always output `regex` and the non-conformant element, instead of `enclosed_atoms`, where it should. So that should be fixed also.

2020-09-11 12:25 UTC, paulo-ferraz-oliveira commented on test/examples/fail_atom_naming_convention.erl
> +    'and_neither-is_this',
I'll add this and update the tests. Thanks.

2020-09-11 12:35 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +    IsEnclosed = is_enclosed_atom(AtomName0, AtomName),
This should do the trick: db917ea. (all those "nasty" atoms were added to the test suite)

2020-09-11 12:50 UTC, elbrujohalcon commented
Travis is still unhappy :(

2020-09-11 13:00 UTC, paulo-ferraz-oliveira commented
> Travis is still unhappy :(

It doesn't like `string:replace/4` on OTP 19.3.

2020-09-11 13:02 UTC, elbrujohalcon commented
Then why not just using good ol' pattern-matching over lists?
```erlang
{IsEnclosed, AtomName} =
  case AtomName0 of
    [$'|Rest] ->
      [$'|Reversed] = lists:reverse(Rest),
      {true, lists:reverse(Reversed)};
    AtomName0 ->
      {false, AtomName0}
  end,
```

2020-09-11 13:32 UTC, paulo-ferraz-oliveira commented
> Then why not just using good ol' pattern-matching over lists?
> 
> ```erlang
> {IsEnclosed, AtomName} =
>   case AtomName0 of
>     [$'|Rest] ->
>       [$'|Reversed] = lists:reverse(Rest),
>       {true, lists:reverse(Reversed)};
>     AtomName0 ->
>       {false, AtomName0}
>   end,
> ```

I can use this, but I do see a benefit to using less code to achieve the same result.

2020-09-11 13:47 UTC, merged