Decrease chance of error and improve maintenance
inaka/elvis_core pull request #135
Opened 2020-09-17 23:55 UTC by paulo-ferraz-oliveira

I found different defaults in `elvis_style` and `elvis_rulesets`, and in those cases the public Wiki won.

[Fix inaka/elvis#525].

2020-09-17 23:57 UTC, paulo-ferraz-oliveira commented on test/style_SUITE.erl
> +    [] = elvis_style:operator_spaces(ElvisConfig, Path, #{rules=>[]}),
Broken because you now have to be explicit about what you're overriding.

2020-09-17 23:57 UTC, paulo-ferraz-oliveira commented on test/style_SUITE.erl
> +    [] = elvis_style:operator_spaces(ElvisConfig, Path, #{rules => []}),
Broken because you now have to be explicit about what you're overriding.

2020-09-17 23:58 UTC, paulo-ferraz-oliveira commented
This isn't yet complete, but if the general direction isn't this one, I'll want to adapt before I move to the other rulesets.

2020-09-18 00:02 UTC, paulo-ferraz-oliveira commented
Anyway, I had a local version that used macros for functions `default/2` and `option`. It simplified stuff, but may not be what you wanted.

Basically, where you have 
```erlang
option(OptionName, RuleConfig, Rule)
```
you'd have
```erlang
?OPT(OptionName)
```
with 
```erlang
-define(OTP(OptionName), (fun () -> maps:get(OptionName, RuleConfig, default(?FUNCTION_NAME, OptionName)) end))
```
(with the assumption that `RuleConfig` was defined in the call context - I know, "dirty").

2020-09-18 00:05 UTC, paulo-ferraz-oliveira commented
I then added a further change where `default(?FUNCTION_NAME, OptionName)` would also become
```erlang
-define(?DEF(OptionName), OptionName => default(?FUNCTION_NAME, OptionName)).
% so we could build the options maps as:
#{ ?DEF(limit) },
```

2020-09-18 00:37 UTC, paulo-ferraz-oliveira commented
Why these (local) changes?

I just feel that defining stuff as
```erlang
    #{ limit => default(god_modules, limit)
     , ignore => default(god_modules, ignore)
```
is more error-prone than (though the advantage is there's no "magic")
```erlang
    #{ ?DEF(limit)
     , ?DEF(ignore) }
```

and also I'd prefer to reduce stuff like
```erlang
    Regex = option(regex, RuleConfig, function_naming_convention),
    Ignores = option(ignore, RuleConfig, function_naming_convention),
```
to
```erlang
    Regex = ?OPT(regex),
    Ignores = ?OPT(ignore),
```
thus removing the need to keep using `RuleConfig` and the function name (or `?FUNCTION_NAME`).

2020-09-18 00:38 UTC, paulo-ferraz-oliveira commented
I pushed a preparation commit for those (macro-based) changes should we want them in `elvis_style`.

2020-09-18 06:03 UTC, elbrujohalcon requested changes

2020-09-18 06:03 UTC, elbrujohalcon commented on src/elvis_style.erl
> +default(line_length, limit) -> 100;
Why do we need 2 different `default` functions? Can't these values just be embedded in `default/1`?

2020-09-18 06:07 UTC, elbrujohalcon commented
Oh, and please move us to `meck 0.9.0` 🙏

2020-09-18 09:40 UTC, elbrujohalcon commented
Sorry, @paulo-ferraz-oliveira … but we have a rule [against macros](https://github.com/inaka/erlang_guidelines#no-macros).
I'm inclined to reluctantly allow `?FUNCTION_NAME`… although I would not use that myself. But that's like… the farthest I'm willing to go in that direction.

2020-09-18 09:42 UTC, paulo-ferraz-oliveira commented on src/elvis_rulesets.erl
> +        , atom_naming_convention ]);
I'm getting used to it. It's not something I do in my everyday projects.

2020-09-18 09:44 UTC, elbrujohalcon requested changes

2020-09-18 09:44 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    maps:get(OptionName, RuleConfig, maps:get(OptionName, default(Rule))).
To avoid the extra steps if they're not needed…
```suggestion
    case RuleConfig of
        #{OptionName := Value} -> Value;
        _ -> maps:get(OptionName, default(Rule))
    end.
```

even better if you can fit that into two function clause heads.

2020-09-18 09:44 UTC, paulo-ferraz-oliveira commented on src/elvis_rulesets.erl
> +        , atom_naming_convention ]);
df1fea8

2020-09-18 09:45 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +default(line_length, limit) -> 100;
They can: 146849a

2020-09-18 09:46 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +                                                     , {erlang, size, 1}].
df1fea8

2020-09-18 09:46 UTC, paulo-ferraz-oliveira commented
> Oh, and please move us to `meck 0.9.0` 🙏

I didn't want to change it, since it wasn't affecting the scope of my PR. But I'll do it, as per your request.

2020-09-18 09:50 UTC, paulo-ferraz-oliveira commented
> Sorry, @paulo-ferraz-oliveira … but we have a rule [against macros](https://github.com/inaka/erlang_guidelines#no-macros).
> I'm inclined to reluctantly allow `?FUNCTION_NAME`… although I would not use that myself. But that's like… the farthest I'm willing to go in that direction.

Hm... I guess it never made it to `elvis`. It is proposed [here](https://github.com/inaka/elvis/issues/119) though. We'll eventually get there :)

2020-09-18 09:55 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +    maps:get(OptionName, RuleConfig, maps:get(OptionName, default(Rule))).
I was going to propose that but then you said it wouldn't degrade performance :D.

2020-09-18 09:59 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +    maps:get(OptionName, RuleConfig, maps:get(OptionName, default(Rule))).
d1a8d02

2020-09-18 10:01 UTC, paulo-ferraz-oliveira commented
@elbrujohalcon, don't merge just yet; there's stuff missing for `elvis_project`. (I just wanted to understand if I was going in the right direction)

2020-09-18 10:23 UTC, elbrujohalcon approved these changes
Is it ready now, @paulo-ferraz-oliveira ?

2020-09-18 16:30 UTC, paulo-ferraz-oliveira commented
It is.

2020-09-18 16:56 UTC, merged