Allow module-level configuration via attribute `-elvis(_)`
inaka/elvis_core pull request #136
Opened 2020-09-19 00:17 UTC by paulo-ferraz-oliveira

[Fix inaka/elvis#529]

I just wanted to push this soon to get some guidance before continuing. **Not to be merged yet**.

I get the `-elvis(_).` attribute from the parse file tree; I use it to override potential `elvis.config` -level rules.
Is this the expected behavior (module-level overrides project-level)?

What's missing, still?
1. tests,
2. `{function(), arity()}` where we find `module`,
3. `{function()}` where we find `module` (should this one exist?),
4. anything else?

2020-09-21 07:18 UTC, elbrujohalcon reviewed
I think we should somehow try to reuse the code in `elvis_config` to merge rules.
Besides that. How will the `elvis` attribute look like in files?

I imagine something like the following…

```erlang
-elvis([{elvis_style, state_record_and_type, disable}]).
-elvis([{elvis_style, line_length, #{limit => 150, skip_comments => false}},
            {elvis_style, nesting_level, #{level => 2}}]).
```

i.e. lists of rule exceptions just like the ones you can find on the `rules` attribute in `elvis.config`.

2020-09-21 07:18 UTC, elbrujohalcon commented on src/elvis_core.erl
> +merge_rules(ElvisConfigRules, {file, ParseTree}) ->
`elvis_config` already has a `merge_rules/2` function that merges rules and understands about `disable` and all that. Can't we just export that function and somehow use it from there?

2020-09-21 07:22 UTC, elbrujohalcon commented
> I get the `-elvis(_).` attribute from the parse file tree; I use it to override potential `elvis.config` -level rules.
> Is this the expected behavior (module-level overrides project-level)?

Yes.
 
> 2. `{function(), arity()}` where we find `module`,
> 3. `{function()}` where we find `module` (should this one exist?),

I wasn't expecting `module` to be found anywhere. `-elvis` should only apply to the module that's being currently analyzed. `{function(), arity()}` and/or `function()` are things that I would gladly leave for a long distant future… If people really really get used to `-elvis` so much that they require us to add support for particular rules-by-function configuration, then we do it… but otherwise… I would ignore it for now.

> 4. anything else?

Proper documentation…

2020-09-21 09:17 UTC, paulo-ferraz-oliveira commented on src/elvis_core.erl
> +merge_rules(ElvisConfigRules, {file, ParseTree}) ->
Most surely. I didn't know about it, so might have reinvented the wheel here a bit. :-)

2020-09-21 09:18 UTC, paulo-ferraz-oliveira commented
The inspiration for `#{ module => Rules }` actually came from your original comment [here](https://github.com/inaka/elvis/issues/488#issuecomment-402118939), but it's easily removable.

2020-09-21 09:25 UTC, elbrujohalcon commented
> The inspiration for `#{ module => Rules }` actually came from your original comment [here](https://github.com/inaka/elvis/issues/488#issuecomment-402118939), but it's easily removable.

Right… My bad.
I went way over my head with that suggestion… At least for the first step, I would recommend keeping things simpler.

First, let's make this work in an easy and intuitive way… and then we can make them more complex if needed.

2020-09-22 23:30 UTC, paulo-ferraz-oliveira commented on src/elvis_core.erl
> +merge_rules(ElvisConfigRules, {file, ParseTree}) ->
1ee5c3d

2020-09-22 23:49 UTC, paulo-ferraz-oliveira commented
I wrote an initial draft of the documentation for this [here](https://github.com/inaka/elvis/issues/535). Let me know.

I think we're only missing tests now.

2020-09-22 23:54 UTC, paulo-ferraz-oliveira commented on src/elvis_core.erl
> +-spec main([]) -> ok | {fail, [elvis_result:file()]}.
This is a very basic attempt (though working) at consuming our own produce. Comment away.

2020-09-22 23:55 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> -                = enclosed_atoms_regex_or_same(option(enclosed_atoms, RuleConfig, atom_naming_convention), Regex),
Because of `rock`'s results.

2020-09-22 23:55 UTC, paulo-ferraz-oliveira commented on elvis.config
> +                  {elvis_style, god_modules, #{ignore => [elvis_style]}}],
Because of `rock`'s results.

2020-09-23 01:14 UTC, elbrujohalcon approved these changes
I like this.

2020-09-23 01:14 UTC, elbrujohalcon commented on src/elvis_core.erl
> +    lists:foldl(
Can we use `lists:flatmap/2` or a list comprehension for this?

2020-09-23 08:44 UTC, paulo-ferraz-oliveira commented on src/elvis_core.erl
> +    lists:foldl(
Sure. Not used to `flatmap`, but can give it a go... Looking at the code, though, a list comprehension seems more appropriate.

2020-09-23 08:48 UTC, paulo-ferraz-oliveira commented on src/elvis_core.erl
> +    lists:foldl(
87573b3

2020-09-23 08:52 UTC, elbrujohalcon requested changes

2020-09-23 08:52 UTC, elbrujohalcon commented on src/elvis_core.erl
> +    [ktn_code:attr(value, ElvisAttr) || ElvisAttr <- ElvisAttrs].
Shouldn't this be a flat list instead?
```suggestion
    [Rule || ElvisAttr <- ElvisAttrs, Rule <- ktn_code:attr(value, ElvisAttr)].
```

2020-09-23 08:52 UTC, elbrujohalcon commented on src/elvis_core.erl
> +    [ktn_code:attr(value, ElvisAttr) || ElvisAttr <- ElvisAttrs].
I guess the tests will catch these things…

2020-09-23 08:54 UTC, elbrujohalcon commented on src/elvis_core.erl
> +%% for eating what we cook
```suggestion
%% for eating our own dogfood
```
[(It's a more common idiom in English)](https://en.wikipedia.org/wiki/Eating_your_own_dog_food)

2020-09-23 08:54 UTC, paulo-ferraz-oliveira commented
How about we add `rebar_cmd` and add make `rock` into an `elvis_core` command?

Something like:
```erlang
% rebar.config
{plugins, [rebar_cmd]}.
{commands, [{rock, "rebar3 escriptize && _build/default/bin/elvis_core"}]}.
{alias, [{rock, [{cmd, "rock"}]}]}.
```

_Rocking with Elvis_ would be possible via `rebar3 rock` (and would could also simplify `.travis.yml`).

2020-09-23 08:56 UTC, paulo-ferraz-oliveira commented on src/elvis_core.erl
> +%% for eating what we cook
b83efdf

2020-09-23 09:00 UTC, paulo-ferraz-oliveira commented on src/elvis_core.erl
> +    [ktn_code:attr(value, ElvisAttr) || ElvisAttr <- ElvisAttrs].
Yup.

2020-09-23 09:25 UTC, paulo-ferraz-oliveira commented
Ah, wait, `"rebar3 escriptize && _build/default/bin/elvis_core"` wouldn't work in `rebar_cmd`: there's still [a feature that needs fixing 😄](https://github.com/gootik/rebar_cmd/issues/22).  But I can plug escriptize to compile and get it done.

2020-09-23 09:34 UTC, elbrujohalcon commented
> Ah, wait, `"rebar3 escriptize && _build/default/bin/elvis_core"` wouldn't work in `rebar_cmd`: there's still [a feature that needs fixing 😄](https://github.com/gootik/rebar_cmd/issues/22). But I can plug escriptize to compile and get it done.

Can't we… `erl -s elvis_core main` instead?

2020-09-23 09:47 UTC, paulo-ferraz-oliveira commented
https://github.com/inaka/elvis_core/pull/136/commits/d110f78a6f882bc8e4535be8fd141c508600efbc: what's happening here?

1. `rebar_cmd` is used for `rebar3 cmd <command>` -like execution,
2. an `alias` is created for us to do `rebar3 rock` instead of `rebar3 cmd rock`,
3. we're hooking on post-compile since `rebar_cmd` can't (as of this moment) understand `;` or `&&` properly, in shell commands ([it'll probably be taken care of, in the near future](https://github.com/gootik/rebar_cmd/issues/22)),
4. we ran our `escript` so we eat our own dogfood!

2020-09-23 09:48 UTC, paulo-ferraz-oliveira commented
> Can't we… erl -pa $(rebar3 path) -s elvis_core main instead?

We can, but it's not intuitive, is it? Let me know what you think about this latest commit.

2020-09-23 10:05 UTC, elbrujohalcon requested changes
Cool! Only the tests are missing.

2020-09-24 15:18 UTC, paulo-ferraz-oliveira commented
```erlang
{ok, #{ rules := [ #{ items := [] } ]}} = elvis_core:do_rock(File, ElvisConfig).
```
seems to indicate "no items disrespect any of the rules".

On the other hand,
```erlang
{ok, #{ rules := [] }} = elvis_core:do_rock(File, ElvisConfig).
```
seems to indicate "no rules were present", or even "no items were analyzed on existing rules". This seems odd (but perhaps I'm mis-interpreting the interface), especially when rules are analyzed but respected.

2020-09-24 20:59 UTC, paulo-ferraz-oliveira commented on config/test.config
> +        ruleset => erl_files
I added these to improve testing targets. In any case I'll refer to this further below.

2020-09-24 21:00 UTC, paulo-ferraz-oliveira commented on src/elvis_core.erl
> +                                       merge_rules({file, ParseTree}, lists:flatten(Rules))),
I added this `lists:flatten` otherwise we'd be "merging" a list with a list of lists, and that lead to odd results. I can expand on it, if you feel uncomfortable with this.

2020-09-24 21:01 UTC, paulo-ferraz-oliveira commented on test/elvis_test_utils.erl
> +  RulesetCfgs = application:get_env(elvis_core, config, []),
For the improved testing I mentioned above.

2020-09-24 21:02 UTC, paulo-ferraz-oliveira commented
To create the tests I did the following:
1. picked all fail modules,
2. created the tests as I would see them fail,
3. "fixed" all the modules with `-elvis(_).`,
4. rinsed and repeated until all was Okay.

2020-09-24 21:51 UTC, paulo-ferraz-oliveira commented
Tests are failing remotely, not locally. I'm going to try and compile the same `rebar3` version (that Travis is using) to see if I can replicate it. If so, this means something changed and will probably degrade testing when we get to remote 3.14.1 (the one I'm using locally).

2020-09-25 08:42 UTC, elbrujohalcon commented on config/test.config
> +        rules => [{elvis_project, old_configuration_format}],
Isn't this rule already included in the ruleset?

2020-09-25 08:45 UTC, elbrujohalcon commented on src/elvis_core.erl
> +                                       merge_rules({file, ParseTree}, lists:flatten(Rules))),
No idea why `elvis_config:rules/1` returns a list of lists, but I trust you.

2020-09-25 08:51 UTC, elbrujohalcon requested changes
A few tiny stylish things only.
I ❤️  the new way of testing… it looks very similar to what we have in `rebar3_format`.

2020-09-25 08:51 UTC, elbrujohalcon commented on src/elvis_core.erl
> +    elvis_config:merge_rules(ElvisAttrRules, ElvisConfigRules).
```suggestion
    elvis_config:merge_rules(ElvisAttrRules, ElvisConfigRules).
```
Can't we just avoid the intermediate step? Or is there some sort of recursion I'm not seeing?

2020-09-25 08:51 UTC, elbrujohalcon commented on test/elvis_test_utils.erl
> +  [Cfg || Cfg <- RulesetCfgs, maps:find(ruleset, Cfg) =:= {ok, Ruleset}].
```suggestion
  [Cfg || #{ruleset := R} = Cfg <- RulesetCfgs, R =:= Ruleset].
```
I think this should be equivalent to your expression and I think it's a bit clearer.

2020-09-25 10:52 UTC, paulo-ferraz-oliveira commented on src/elvis_core.erl
> +                                       merge_rules({file, ParseTree}, lists:flatten(Rules))),
Well, because `rules` is a list of maps 😄 and the maps get turned into lists (thus list of lists). Don't trust me, but the tests. If possible we should get a third opinion, no?

2020-09-25 10:52 UTC, paulo-ferraz-oliveira commented on config/test.config
> +        rules => [{elvis_project, old_configuration_format}],
I only added the ruleset element to those maps. I didn't touch anything else, since I didn't "need" to. Should I remove the "by default" elements?

2020-09-25 10:54 UTC, paulo-ferraz-oliveira commented on src/elvis_core.erl
> +    elvis_config:merge_rules(ElvisAttrRules, ElvisConfigRules).
Probably, there's no recursion you're not seeing 😄. The original code [had more function clauses](https://github.com/inaka/elvis_core/pull/136/commits/98a896f4f8797bbf020141b9adbc30eb1015edc3#diff-0e321e7ef4fb27c145572ae07f7ebeacR134), I kept removing them, and simplifying code (as I tested) and got to this. Let me check.

2020-09-25 10:56 UTC, paulo-ferraz-oliveira commented on src/elvis_core.erl
> +    elvis_config:merge_rules(ElvisAttrRules, ElvisConfigRules).
I wonder if this is one of those cases the pre-compiler tools optimizes. 🤔

2020-09-25 10:56 UTC, paulo-ferraz-oliveira commented on src/elvis_core.erl
> +    elvis_config:merge_rules(ElvisAttrRules, ElvisConfigRules).
dbc0357

2020-09-25 11:01 UTC, paulo-ferraz-oliveira commented
**Unrelated**: I increasingly feel the need to implement `ignore` as a generic option for all rules. It'll probably be the one I'll pick next.

2020-09-25 11:05 UTC, elbrujohalcon commented on config/test.config
> +        rules => [{elvis_project, old_configuration_format}],
yes, please.

2020-09-25 11:36 UTC, paulo-ferraz-oliveira commented on config/test.config
> +        rules => [{elvis_project, old_configuration_format}],
f269a08

2020-09-25 12:07 UTC, elbrujohalcon approved these changes

2020-09-25 12:07 UTC, merged

2020-09-25 14:23 UTC, paulo-ferraz-oliveira commented
❤️ thanks much.