Feature option ignore in all rules
inaka/elvis_core pull request #137
Opened 2020-10-02 01:13 UTC by paulo-ferraz-oliveira

[Fix inaka/elvis#507]
[Fix inaka/elvis#488]

As per previous discussions, this initial implementation step can be seen as a request for comments. I will also comment the code on some decisions and what I'd like to improve and/or require help.

2020-10-02 01:18 UTC, paulo-ferraz-oliveira commented
So, my naive approach to this problem was:
1. remove `ignore` from the default options list of every rule (the less the merrier) since it'll be handled as a special case,
2. create type `ignorable()` to hold the information at the center of this change,
3. strip all rules of the currently implemented behavior of handling `ignore` on a per rule basis,
4. dig deeper into where we can best apply the filter so changes after that are minimal (ended up being `elvis_file: resolve_parse_tree`).

**Note**: only one test had to be touched, because one of the options disappeared.

2020-10-02 01:20 UTC, paulo-ferraz-oliveira commented on src/elvis_file.erl
> +resolve_parse_tree(false = _ModIsIgnored, ".erl", Content, Mod, Ignore) ->
This seemed like the appropriate place to centralize the filtering capabilities, since I didn't want to have to keep calling a generic function `is_ignored(...)`, inside every rule, with which I'd generate a new case clause (as was).

2020-10-02 01:21 UTC, paulo-ferraz-oliveira commented on src/elvis_file.erl
> +    #{ type => root
Hurrah for non-opaque structures. In any case, I did try with `undefined`, `ignored`, ... and tweaking code affected by this change, but the way it is stuff is simply too tight. Does this seem completely inadequate?

2020-10-02 01:24 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
>      IgnoreModules = option(ignore, RuleConfig, module_naming_convention),
This is the only `ignore` I left in `elvis_style` and for a somewhat good reason: it doesn't parse the tree to apply a rule (only to get a module name). Let me know if there is a better alternative.

2020-10-02 14:29 UTC, elbrujohalcon commented on src/elvis_file.erl
> +resolve_parse_tree(false = _ModIsIgnored, ".erl", Content, Mod, Ignore) ->
I like your approach. 👍

2020-10-02 14:31 UTC, elbrujohalcon commented on src/elvis_file.erl
> +    #{ type => root
So… you're returning an empty AST here so that the rules have nothing to review? It's clever, but please add a comment explaining the reasoning.

2020-10-02 14:39 UTC, elbrujohalcon reviewed
I would've naively added the code to ignore modules to `elvis_core:apply_rule/2` instead of adding it to every rule, but I understand why you did it this way (i.e. to support specific function ignores).
Nevertheless, maybe you want to consider moving the ignoring code for modules to `elvis_core:apply_rule/2`, and then filtering the `ignore` list in the options to remove the module names before passing it in to the application of every rule.

2020-10-02 23:49 UTC, paulo-ferraz-oliveira commented on src/elvis_file.erl
> +    #{ type => root
I'll add the comment with the reasoning, but I disagree it's clever 😄; I find it rather dirty, but it serves the purpose at hand (at least until `ktn` decides to change the structure - in which case many other things in `elvis_core` would also have to be reviewed).

2020-10-02 23:51 UTC, paulo-ferraz-oliveira commented
> I would've naively added the code to ignore modules to `elvis_core:apply_rule/2` instead of adding it to every rule, but I understand why you did it this way (i.e. to support specific function ignores).
> Nevertheless, maybe you want to consider moving the ignoring code for modules to `elvis_core:apply_rule/2`, and then filtering the `ignore` list in the options to remove the module names before passing it in to the application of every rule.

Sure, I can give this a try. Thanks.

2020-10-05 21:06 UTC, paulo-ferraz-oliveira commented on src/elvis_file.erl
> +    #{ type => root
a52fc4e

2020-10-05 21:08 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
>      IgnoreModules = option(ignore, RuleConfig, module_naming_convention),
@elbrujohalcon: I see that `line_length`, `no_spaces`, `no_tabs`, and `no_trailing_whitespace` are also not "under" my change, since they're (I consider them, at least) more style oriented, in a "project"-oriented analysis.

Should I:
1. not care that `ignore` doesn't work for these, as is now (in the PR)?
2. make `ignore` work for this on a module-level, as probably another comment will take care of?
3. move these to `{elvis_project, _, _}` since they seem more high-level than other rules?

2020-10-05 23:25 UTC, paulo-ferraz-oliveira commented on src/elvis_core.erl
> +-export([apply_rule/2]).
Exposed, since now tests are using it because ignore is no longer at the rule execution -level, but higher up.

2020-10-06 05:24 UTC, elbrujohalcon commented on src/elvis_core.erl
> +-export([apply_rule/2]).
Does it work if it's placed between `ifdef`, i.e.…

```erlang
-ifdef(TEST).
-export [apply_rule/2].
-endif.
```

2020-10-06 05:26 UTC, elbrujohalcon commented on src/elvis_style.erl
>      IgnoreModules = option(ignore, RuleConfig, module_naming_convention),
I, as a user, would expect `ignore` directives to be respected for those rules, too.
It would not surprise me to find people wanting to ignore the `no_trailing_whitespace` rule for certain auto-generated modules, for instance.

2020-10-06 05:41 UTC, elbrujohalcon requested changes

2020-10-06 05:41 UTC, elbrujohalcon commented on src/elvis_style.erl
>      IgnoreModules = option(ignore, RuleConfig, module_naming_convention),
I understand that it's not easy to implement that since those rules don't parse the tree and, in general, when we apply them we don't really know where we're standing (i.e. which function are we in).
I think a somewhat reasonable approach would be to…

1. Move all these rules to a different module (`elvis_text_style`, maybe?).
2. Wherever we said that _every rule has an `ignore => ignorable()` config_, amend the text to correctly state that `{M, F} and {M, F, A}` are only valid for  _rules **in `elvis_style`** and not in other rule modules_.

…or maybe…

2. Split the config params into `ignore => [module()], ignore_functions => [ignorable()]` and make this second one `elvis_style`-exclusive.

I think that would be safe and it would also prevent people from assuming that other modules (outside `elvis_style`) will support `ignore`.

2020-10-06 09:11 UTC, paulo-ferraz-oliveira commented on src/elvis_core.erl
> +-export([apply_rule/2]).
It should.

2020-10-06 09:13 UTC, paulo-ferraz-oliveira commented on src/elvis_core.erl
> +-export([apply_rule/2]).
711b970

2020-10-06 09:17 UTC, paulo-ferraz-oliveira commented
> Move all these rules to a different module (elvis_text_style, maybe?).

Just noting this IS a breaking change. But it's the one I'll go with.

2020-10-06 09:20 UTC, elbrujohalcon commented
> > Move all these rules to a different module (elvis_text_style, maybe?).
> 
> Just noting this IS a breaking change. But it's the one I'll go with.

Yes, it is. It will require a nice jump in minor version. Maybe mayor version, too? 🤔  SemVer is tricky…

2020-10-06 09:40 UTC, paulo-ferraz-oliveira commented
> > > Move all these rules to a different module (elvis_text_style, maybe?).
> > 
> > 
> > Just noting this IS a breaking change. But it's the one I'll go with.
> 
> Yes, it is. It will require a nice jump in minor version. Maybe mayor version, too? 🤔 SemVer is tricky…

It's not that tricky :D

Major = interface broke
Minor = new feature added (compatible with previous version)
Patch = bug fix (compatible with previous version)

You initially need to decide what is part of your application's interface, though. (e.g. "internal" functions might be exposed in Erlang modules, but not be part of the interface).

In `elvis_core`'s case, for example:
1. the API is part the interface,
2. the `elvis.config` file is part of the interface, and, to a certain extent,
3. the output is part of the interface.

You can also look at it this way: if somebody imports my lib. will they have to change anything to make it work properly with this new version? If so, then the interface was broken; major bump.

2020-10-06 09:46 UTC, elbrujohalcon commented
Cool… so a major bump should be.
OTOH we can do it more slowly… we can keep the functions on `elvis_style`, with something like…

```erlang
-deprecated({no_tabs, 3, next_major_release}).
-spec no_tabs(elvis_config:config(), elvis_file:file(), empty_rule_config()) -> [elvis_result:item()].
no_tabs(Config, Target, RuleConfig) ->
  elvis_text_style(Config, Target, RuleConfig).
```

Then we remove it on the next major release.
I'm not sure if it's worth the hassle, but it may reduce the number of angry users if there is any.

2020-10-06 10:32 UTC, paulo-ferraz-oliveira commented
> if there is any.

Users? Or angry users? 🤣 

I can break the interface, no problem. It's just a question of moving your function name, in any case. (what I usually do is have a `MIGRATION.md` file with instructions on how to migrate when breaking changes occur)

2020-10-06 11:37 UTC, elbrujohalcon commented
> > if there is any.
> 
> Users? Or angry users? 🤣
> 

Yes. :trollface: 

> I can break the interface, no problem. It's just a question of moving your function name, in any case. (what I usually do is have a `MIGRATION.md` file with instructions on how to migrate when breaking changes occur)

`MIGRATION.md` is a great idea!!
Let's break the interface, add `MIGRATION.md`, and move to `1.0.0` for once! It's, in fact, something we should've done a long long time ago anyway.

2020-10-07 06:34 UTC, elbrujohalcon commented on MIGRATION.md
> +- your `ignore` option (from rule `max_function_length`) to also contain the content of
```suggestion
- your `ignore` option (e.g. from rule `max_function_length`) to also contain the content of
```

The rule was just an example, right?

2020-10-07 06:38 UTC, elbrujohalcon requested changes
Just some tiny tweaks to text.

2020-10-07 06:38 UTC, elbrujohalcon commented on MIGRATION.md
> +- your rule config. files (e.g. `elvis.config`), by moving `elvis_style` to `elvis_text_style` for
```suggestion
- your rule config files (e.g. `elvis.config`), by moving `elvis_style` to `elvis_text_style` for
```

2020-10-07 06:38 UTC, elbrujohalcon commented on MIGRATION.md
> +- your `ignore` option (from rule `max_function_length`) to also contain the content of
```suggestion
- your `ignore` option from rule `max_function_length` to also contain the content of
```

2020-10-07 09:37 UTC, paulo-ferraz-oliveira commented on MIGRATION.md
> +- your rule config. files (e.g. `elvis.config`), by moving `elvis_style` to `elvis_text_style` for
I'm going to use "configuration" then. "config"'s not a word, which is why I used the . for abbreviation.

2020-10-07 09:39 UTC, paulo-ferraz-oliveira commented on MIGRATION.md
> +- your rule config. files (e.g. `elvis.config`), by moving `elvis_style` to `elvis_text_style` for
8afb76f

2020-10-07 09:39 UTC, paulo-ferraz-oliveira commented on MIGRATION.md
> +- your `ignore` option (from rule `max_function_length`) to also contain the content of
8afb76f

2020-10-07 09:40 UTC, paulo-ferraz-oliveira commented on MIGRATION.md
> +- your rule config. files (e.g. `elvis.config`), by moving `elvis_style` to `elvis_text_style` for
I also update 0.7.0 to 0.x and 1.0.0 to 1.x, since we don't actually know the departure and arrival version for the consumer, so it's safer to say "if you're bumping into 1.x, from 0.x", since 2.x will surely involve a new `MIGRATION.md` round of updates.

2020-10-07 09:42 UTC, elbrujohalcon commented on MIGRATION.md
> +- your rule config. files (e.g. `elvis.config`), by moving `elvis_style` to `elvis_text_style` for
I like your ideas and your strictness :P

2020-10-09 23:16 UTC, paulo-ferraz-oliveira commented
@elbrujohalcon, anything missing?

2020-10-13 06:29 UTC, merged