Allow for custom rules in elvis configuration
inaka/elvis_core pull request #141
Opened 2020-11-25 15:04 UTC by cnasten

If using multiple RuleGroups with custom made rules, instead of having
to duplicate the rules support a custom rules section of the configuration
that can be referenced in the rules argument:

[
 {
  elvis,
  [
   {rules,
    #{project => [{elvis_style, no_tabs}]}
   },
   {config,
    #{rules => {custom_rules, project}}
   }
  ]
 }
].

2020-11-25 15:11 UTC, elbrujohalcon requested changes
Please consider using the existing rulesets infrastructure for this as much as possible.
Thanks.

2020-11-25 15:11 UTC, elbrujohalcon commented on config/elvis-test-custom-rules.config
> +   {rules,
I would call these `rulesets`.

2020-11-25 15:11 UTC, elbrujohalcon commented on config/elvis-test-custom-rules.config
> +       rules => {custom_rules, project}}]
I would not use `rules` for this. I would instead use the already existing `ruleset` key.

2020-11-25 15:11 UTC, elbrujohalcon commented on config/elvis-test-custom-rules.config
> +       rules => {custom_rules, project}}]
And I would not require the tuple, the atom alone should do (as long as it doesn't collide with the existing rulesets. Or we can even choose to allow users to override them.

2020-11-25 16:41 UTC, cnasten commented on config/elvis-test-custom-rules.config
> +   {rules,
👍

2020-11-25 16:42 UTC, cnasten commented on config/elvis-test-custom-rules.config
> +       rules => {custom_rules, project}}]
What do you think about the updated version? More to your liking or had you something else in mind? :)

2020-11-25 17:53 UTC, elbrujohalcon requested changes
Just a few mostly cosmetic changes.

2020-11-25 17:53 UTC, elbrujohalcon commented on src/elvis_rulesets.erl
> +-define(RULESET_TABLE, elvis_custom_rulesets).
Don't use a macro, just use the atom everywhere. It should be fine.

2020-11-25 17:53 UTC, elbrujohalcon commented on src/elvis_rulesets.erl
> +-define(RULESET_TABLE, elvis_custom_rulesets).
Or alternatively, you can use `?MODULE` as the table name.

2020-11-25 17:53 UTC, elbrujohalcon commented on src/elvis_rulesets.erl
> +    end.
```suggestion
    try ets:lookup_element(?RULESET_TABLE, Group, 2)
    catch
        error:badarg -> []
    end.
```

2020-11-25 17:53 UTC, elbrujohalcon commented on src/elvis_config.erl
> +    lists:foreach(fun({Name, Rules}) ->
Should we drop and recreate the table here (with something like `elvis_rulesets:clean()` or something)?
Just in case someone runs `elvis_core:rock(…)` multiple times with different configurations on each.

2020-11-26 06:47 UTC, elbrujohalcon approved these changes

2020-11-26 06:50 UTC, elbrujohalcon commented
**Thank you, @cnasten!**

Do you mind adding documentation about this new feature to [the wiki](https://github.com/inaka/elvis_core/wiki/Rules).

It would be awesome if you can actually add a whole new section about _Rulesets_, briefly explaining that there are some predefined ones but you can also define your own ones… etc…

2020-11-26 06:50 UTC, merged

2025-07-10 16:46 UTC, paulo-ferraz-oliveira commented
@elbrujohalcon, I don't see mention of custom rules, but only custom rulesets. Do we actually support custom rules (as in module+function+def, and centralised execution)?

2025-07-10 16:50 UTC, paulo-ferraz-oliveira commented on src/elvis_config.erl
> +    lists:foreach(fun({Name, Rules}) ->
> Just in case someone runs elvis_core:rock(…) multiple times with different configurations on each.

I mean, this seems like an edge case, and given the current implementation we're dropping the table and recreating it multiple times, so it'd probably be better to expose the "drop" interface and then let `elvis_core:` call it directly (?)

2025-07-10 16:51 UTC, elbrujohalcon commented
Short answer, since I'm on the phone: Yes, you add whatever you want to the `rules` list. You can put your own rules there.

2025-07-10 18:45 UTC, paulo-ferraz-oliveira commented
Ok, seems undocumented, though, but I'm probably missing something.

2025-07-11 07:49 UTC, elbrujohalcon commented
OK. Long(er) answer now…

@paulo-ferraz-oliveira The thing is that you don't need to _define_ custom rules as such. They can _just exist_. It's different with custom ruelesets because you do need to define them in the configuration. There is no section for custom rules, you can just _use them_.

The (somewhat hidden) documentation is here: https://github.com/inaka/elvis_core?tab=readme-ov-file#user-defined-rules

It can be made more prominent, if needed.

2025-07-11 16:23 UTC, paulo-ferraz-oliveira commented
Sure, but since I'm trying to validate the config. I'm sure validating that at least custom rules are 2-tuple/3-tuple and refer to existing module:function would be appreciated. And that's what I'm aiming for.