Allow for analysis under rebar3_hank
inaka/elvis_core pull request #200
Opened 2021-07-25 23:13 UTC by paulo-ferraz-oliveira

(also add xref to the analysis)

2021-07-25 23:14 UTC, paulo-ferraz-oliveira commented on src/elvis_project.erl
> +            old_configuration_format/3,
This is part of a non-declared behaviour. It would be great to have the dynamic callback declarations here 😄

2021-07-25 23:37 UTC, paulo-ferraz-oliveira commented on .github/workflows/ci.yml
> -        otp_vsn: [20, 21, 22, 23, 24]
`rebar3_hank` is 21+

2021-07-26 05:41 UTC, elbrujohalcon requested changes

2021-07-26 05:41 UTC, elbrujohalcon commented on src/elvis_project.erl
> +            old_configuration_format/3,
A comment stating just that above this line would be useful.

2021-07-26 05:43 UTC, paulo-ferraz-oliveira commented on src/elvis_project.erl
> +            old_configuration_format/3,
Sure, I'll add it later.

2021-07-26 10:40 UTC, paulo-ferraz-oliveira commented on src/elvis_project.erl
> +            old_configuration_format/3,
Handled with

```erlang
% These are part of a non-declared "behaviour"
% The reason why we don't try to handle them with different arity is
%  that arguments are ignored in different positions (1 and 3) so that'd
%  probably be messier than to ignore the warning
```

Also, I rebased on top of `master`.

2021-07-26 11:47 UTC, elbrujohalcon approved these changes

2021-07-26 11:47 UTC, merged