Fix 210: New rule for behavior vs behaviour.
inaka/elvis_core pull request #212
Opened 2021-10-03 22:36 UTC by jackyhui96

2021-10-04 06:06 UTC, elbrujohalcon requested changes
Thank you very much, @jackyhui96 !!
Two minimal adjustments and it will be ready to be merged :)

2021-10-04 06:06 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    #{ spelling_type => american
Instead of… or on top of `american / british`… I would like to accept the actual words.
In other words, I would like to use this as the configuration for the rule…
```erlang
{elvis_style, behaviour_spelling, #{spelling_type => behaviour}}
```

2021-10-04 06:06 UTC, elbrujohalcon commented on src/elvis_style.erl
> +incorrect_behaviour_spelling(Config, Target, RuleConfig) ->
Please rename the rule as `behaviour_spelling`. We try our best to use _positive_ names for the rules :)

2021-10-04 06:07 UTC, elbrujohalcon commented on src/elvis_style.erl
> +            ResultFun = result_node_line_fun(?INCORRECT_BEHAVIOuR_SPELLING(SpellingType)),
```suggestion
            ResultFun = result_node_line_fun(?INCORRECT_BEHAVIOUR_SPELLING(SpellingType)),
```

2021-10-04 17:26 UTC, jackyhui96 commented
Will work on the changes now and push up, could you label it with hacktoberfest so it counts towards it please? :) Was meant to add this to your original issue which has the label but not sure on the correct process to do that

2021-10-05 06:23 UTC, elbrujohalcon requested changes
I updated the repo tags (It had `hacktober` instead of `hacktoberfest` 🤦🏻 ).
I left a few suggestions to improve the code, too.
Besides them, now that we no longer support `american`/`british` as spelling types, I would be tempted to rename `spelling_type` as `proper_spelling`, or just `spelling`. What do you think?

2021-10-05 06:23 UTC, elbrujohalcon commented on src/elvis_style.erl
> +        ++ atom_to_list(SpellingType) ++ " spelling.").
```suggestion
-define(BEHAVIOUR_SPELLING(SpellingType),
        "The behavior/behaviour in line ~p is misspelt, please use the "
        "~p spelling.").
```
And then just pass the atom in when building the message.

2021-10-05 06:23 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    #{ spelling_type => behavior
```suggestion
    #{ spelling_type => behaviour
```
I checked the source code for OTP and [`behaviour`](https://github.com/erlang/otp/search?q=behaviour) is much more popular than [`behavior`](https://github.com/erlang/otp/search?q=behavior). I think that the one with the `u` should be the default.

2021-10-05 06:23 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    #{ spelling_type => behavior
Also in general…
* [~167K uses of `behaviour`](https://github.com/search?q=%22-behaviour%22&type=Code&l=Erlang).
* [~8K uses of `behavior`](https://github.com/search?q=%22-behavior%22&type=Code&l=Erlang).

2021-10-05 06:23 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    #{ spelling_type => behavior
Even your rule is called `behavioUr_spelling` :P

2021-10-05 06:23 UTC, elbrujohalcon commented on src/elvis_style.erl
> +            end
```suggestion
            NodeType /= SpellingType
```

2021-10-05 14:13 UTC, jackyhui96 commented on src/elvis_style.erl
> +            end
I still need to check the Node is a type of behaviour, so I've used the below. Any objections?
`lists:member(NodeType, [behaviour, behavior]) andalso NodeType /= Spelling`

2021-10-05 14:39 UTC, elbrujohalcon commented on src/elvis_style.erl
> +            end
It's brilliant! 🧐

2021-10-05 14:41 UTC, elbrujohalcon requested changes
This is great, @jackyhui96! Thank you very much!
The only missing things are to add the new rule to the list of default rules for `erl_files` and `beam_files` rulesets and to update [the wiki](https://github.com/inaka/elvis_core/wiki/Rules).

2021-10-05 17:35 UTC, jackyhui96 commented
> This is great, @jackyhui96! Thank you very much! The only missing things are to add the new rule to the list of default rules for `erl_files` and `beam_files` [rulesets](https://github.com/inaka/elvis_core/blob/master/src/elvis_rulesets.erl) and to update [the wiki](https://github.com/inaka/elvis_core/wiki/Rules).

No worries @elbrujohalcon, happy to help and contribute! I've updated the [the wiki](https://github.com/inaka/elvis_core/wiki/Rules) and pushed the default rule changes now

2021-10-06 06:15 UTC, elbrujohalcon commented
Woah! Now we found other tests are broken… 🤦🏻

2021-10-06 06:23 UTC, elbrujohalcon approved these changes

2021-10-06 06:24 UTC, merged