Add new rule no_macros (defaults to disabled)
inaka/elvis_core pull request #219
Opened 2022-01-06 16:01 UTC by paulo-ferraz-oliveira

Closes #160 

I'll leave some comments in the code regarding decisions or the lack thereof.

2022-01-06 19:03 UTC, paulo-ferraz-oliveira commented on config/test.config
> +                  {elvis_style, no_macros}
This effectively activates the check for all our tests (which causes required changes to the test suites, as seen below).

2022-01-06 19:04 UTC, paulo-ferraz-oliveira commented on src/elvis_config.erl
> +               ({_FileName, _RuleName}) -> true; % not disabled
We were not considering the fact that a rule with no options doesn't necessarily mean `disabled`: hopefully this will surface positives in places where such overrides are being used, though not common (since we had no "disabled by default" rules up until now).

2022-01-06 19:04 UTC, paulo-ferraz-oliveira commented on src/elvis_core.erl
> +apply_rule({_Module, _Function, disable}, {Result, Config, File}) ->
Seems odd to put this here, but required, since when the rule is not overridden it is considered disable (up until now all our rules were either enabled or had an options map, by default).

2022-01-06 19:06 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +-define(PREDEF_MACROS, % from unexported eep:predef_macros/1
Should we act differently here? I don't think the list will change that much and the first one to find a false positive gets to come and PR 😄 (we could also fetch this list dynamically, but 1. extra overhead, 2. we'd have to use a parse transform to avoid that overhead). I'm open to suggestions.

2022-01-06 19:08 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +                    [elvis_result:new(item, ?NO_MACROS_MSG, [Macro, Line]) | Acc]
Results in reverse order to avoid `++` but I'm not sure this is interesting. (I do fix my files from top to bottom, though, since that way I can copy paste the issues to a text file and fixing up won't change line numbers - thus avoiding unnecessary re-runs).

2022-01-06 19:08 UTC, paulo-ferraz-oliveira commented on test/examples/fail_used_ignored_variable.erl
> +-elvis([{elvis_style, no_macros, #{allow => ['__']}}]).
Best macro ever! Very descriptive 😄

2022-01-06 19:10 UTC, paulo-ferraz-oliveira commented on test/style_SUITE.erl
> +            [] = FailRes; % no macros on BEAM files
This also prompted me to review the Rules (they've been updated targeting 1.4.0). Check the diff: https://github.com/inaka/elvis_core/wiki/Rules/_compare/fb9c3a3b655faf66fd37f1d1ef125ed1ded9c592...4bb05900cbb419eee2b01a772ec966258ddcb0cb

2022-01-06 19:13 UTC, paulo-ferraz-oliveira commented
Tests passing. All yours!

2022-01-07 08:27 UTC, elbrujohalcon requested changes
I like this new rule, but instead of making it disabled by default (which, to me, makes little sense), I would just leave it out of the `rulesets`.

2022-01-07 08:27 UTC, elbrujohalcon commented on src/elvis_style.erl
> +-define(PREDEF_MACROS, % from unexported eep:predef_macros/1
It's extra-funny to implement a new rule to avoid macros using yet another macro to keep the list of macros :P
Maybe put this in a function instead?

2022-01-07 08:27 UTC, elbrujohalcon commented on src/elvis_style.erl
> +                    [elvis_result:new(item, ?NO_MACROS_MSG, [Macro, Line]) | Acc]
I don't really care either way.

2022-01-07 08:27 UTC, elbrujohalcon commented on test/examples/fail_used_ignored_variable.erl
> +-elvis([{elvis_style, no_macros, #{allow => ['__']}}]).
🪄

2022-01-07 08:27 UTC, elbrujohalcon commented on test/style_SUITE.erl
> +            [] = FailRes; % no macros on BEAM files
👌🏻

2022-01-07 08:27 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    disable;
I would not have a rule disabled by default. Leave it with options but _outside_ of any rulesets. If users want to use it, they can include it in the `rules` part, which is what they must do in this situation anyway, right?

2022-01-07 12:16 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +-define(PREDEF_MACROS, % from unexported eep:predef_macros/1
I will. I just thought it would be unnecessary overhead, since the macro definition is pre-processed.

2022-01-07 12:20 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +-define(PREDEF_MACROS, % from unexported eep:predef_macros/1
1cd6197

2022-01-07 12:24 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +    disable;
6f88302

2022-01-07 12:27 UTC, paulo-ferraz-oliveira commented
Are the rule's names and options' names Ok?

2022-01-07 14:15 UTC, elbrujohalcon commented
> Are the rule's names and options' names Ok?

Yes.

2022-01-07 14:17 UTC, elbrujohalcon approved these changes

2022-01-07 14:17 UTC, merged

2022-01-07 18:13 UTC, paulo-ferraz-oliveira commented
Wonderful. Thanks for merging.