New Rule: Types term or any
inaka/elvis_core pull request #259
Opened 2022-10-21 22:31 UTC by jackyhui96

#258

2022-10-22 09:33 UTC, paulo-ferraz-oliveira commented
@jackyhui96, if you change your description to e.g. `Closes #258`, it automatically links to that issue.

2022-10-22 09:43 UTC, paulo-ferraz-oliveira reviewed
I ask for a few tweaks but I like the overall direction and implementation.

2022-10-22 09:43 UTC, paulo-ferraz-oliveira commented on RULES.md
> +- [Types Term vs Any](doc_rules/elvis_style/types_term_or_any.md)
```suggestion
- [Types `term()` or `any()`](doc_rules/elvis_style/types_term_or_any.md)
```

2022-10-22 09:43 UTC, paulo-ferraz-oliveira commented on doc_rules/elvis_style/types_term_or_any.md
> +# Types Term vs Any
```suggestion
# Types `term()` or `any()`
```

2022-10-22 09:43 UTC, paulo-ferraz-oliveira commented on doc_rules/elvis_style/types_term_or_any.md
> +  - default: `no_preference`.
I don't think we need a default, in this case, since `elvis_core` will not be opinionated in this sense. The default is to not include the rule... But if we do end up with a default I'd prefer `none` or `undefined`.

2022-10-22 09:43 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +        "The type in line ~p is not preferred, please use the "
I'd go with something like "Found ~p on line ~p, but your preferred type is ~p".

2022-10-22 09:43 UTC, paulo-ferraz-oliveira commented on doc_rules/elvis_style/types_term_or_any.md
> +- `preference :: term | any`.
I'd go with a shorter `prefer` name for the option.

2022-10-22 09:43 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +            Predicate =
We should probably put this predicate in its own private function, just to ease the code flow.

2022-10-22 09:43 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +                        fun(Node) ->
For the same reason above, we should probably separate this anon. function to its own private definition.

2022-10-22 19:31 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +-define(TYPES_TERM_OR_ANY, "Found ~p on line ~p, but your preferred type is ~p.").
```suggestion
-define(TYPES_TERM_OR_ANY, "Found usage of type ~p() on line ~p, but your preferred type is ~p().").
```

2022-10-22 19:34 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +-define(TYPES_TERM_OR_ANY, "Found ~p on line ~p, but your preferred type is ~p.").
You can commit directly from GitHub, too, if you want, by using button "Commit suggestion" above.

2022-10-22 19:35 UTC, paulo-ferraz-oliveira commented
I'm Ok with all the recent changes. I'll approve, assuming you'll eventually accept the only new suggestion I've added. I'll also add @elbrujohalcon as a reviewer so he can give this a look. Many thanks.

2022-10-22 19:35 UTC, paulo-ferraz-oliveira approved these changes

2022-10-24 06:55 UTC, elbrujohalcon requested changes
I like the idea.
I think this rule is very similar to [Behaviour Spelling](https://github.com/inaka/elvis_core/blob/main/doc_rules/elvis_style/behaviour_spelling.md) and so I would expect its implementation, documentation, tests, etc. to be more similar to it..
That's the goal of all the suggestions I made.

Besides that, can you add more tests to showcase the different places where the type can be, like…

```erlang
% Type definitions when this is alone or combined
-type my_type() :: any().
-type combined() :: term() | my_type().

% Callback definitions (with or without when)
-callback my_callback(term()) -> any().
-callback my_callback(X) -> X when X :: term().

% Specs with when
-spec my_spec(X) -> X when X :: any().

% Record definitions
-record(my_record, {t :: term(), a :: any()}).
```

…and can you add tests where this should not be validated, like these…

```erlang
% A parametric type called any
-type any(Thing) :: Thing.

% A function called any
-spec any() -> term().
any() -> any.

% A function that calls the function called any
my_function() -> any().
```

2022-10-24 06:55 UTC, elbrujohalcon commented on doc_rules/elvis_style/types_term_or_any.md
> +- `prefer :: term | any`.
We should specify which one is the default.

2022-10-24 06:55 UTC, elbrujohalcon commented on src/elvis_style.erl
> +        "Found usage of type ~p() on line ~p, but your preferred type is ~p().").
```suggestion
        "Found usage of type ~p/0 on line ~p. Please use ~p/0, instead.").
```

2022-10-24 06:55 UTC, elbrujohalcon commented on RULES.md
> +- [Types `term()` or `any()`](doc_rules/elvis_style/types_term_or_any.md)
```suggestion
- [Consistent Generic Type](doc_rules/elvis_style/consistent_generic_type.md)
```
☝🏻 I'm not sold on this title/name either, but… it would allow us to include `_` in the list if we ever want to also consider that a _generic_ type. I know it's not exactly the same… but in most scenarios, it serves the same purpose as `term()` or `any()`.

2022-10-24 06:55 UTC, elbrujohalcon commented on RULES.md
> +- [Types `term()` or `any()`](doc_rules/elvis_style/types_term_or_any.md)
In other words, I would like the name of this rule not to list all the available options it has.

2022-10-24 06:55 UTC, elbrujohalcon commented on doc_rules/elvis_style/types_term_or_any.md
> +- `prefer :: term | any`.
Also… can we call this parameter something like `preferred_type` or just `type`?

2022-10-24 06:57 UTC, elbrujohalcon commented on doc_rules/elvis_style/types_term_or_any.md
> +  - default: `no_preference`.
I disagree. I think the rule needs a default, so it can be added without specifying options, but the default should be either `term` or `any`.

2022-10-24 06:58 UTC, elbrujohalcon commented on src/elvis_style.erl
> +        "The type in line ~p is not preferred, please use the "
HA! I just recommended changing it back to "Please use…" which would be more similar to other messages we have.

2022-10-24 06:59 UTC, elbrujohalcon commented on doc_rules/elvis_style/types_term_or_any.md
> +- `preference :: term | any`.
…aaand I think the option names should be nouns. What you're choosing is the _preferred type_… so, in my mind, the option should be called `preferred_type` or just `type`, just like the one for _Behaviour Spelling_ is called `spelling`.

2022-10-24 07:01 UTC, elbrujohalcon commented
Sorry for the back and forth, @jackyhui96 … Multiple maintainers, multiple views on the project… 🤷🏻 
If you want, before considering my suggestions, wait for @paulo-ferraz-oliveira to reply to my comments so we can agree on what our preference is.

2022-10-24 12:12 UTC, paulo-ferraz-oliveira commented on doc_rules/elvis_style/types_term_or_any.md
> +- `prefer :: term | any`.
:) It was previously named `preference` and I asked to change to `prefer` (as a verb).

There was also a default (`no_preference`) which I asked to remove, because I'm not sure `elvis_core` should implement this as a default rule (i.e. active from the next release, as it'll force many to change - thus it's considered a breaking change).

2022-10-24 12:12 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +        "Found usage of type ~p() on line ~p, but your preferred type is ~p().").
Yeah, I'd asked to change this, too. I believe "but your preferred type is" is more explicit, since it was the one actually chosen is the options (if we decide to keep the "no default" behaviour).

2022-10-24 12:13 UTC, paulo-ferraz-oliveira commented on RULES.md
> +- [Types `term()` or `any()`](doc_rules/elvis_style/types_term_or_any.md)
I guess this came from the issue title, but I'm Ok with your new suggestion.

2022-10-24 12:14 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +        "Found usage of type ~p() on line ~p, but your preferred type is ~p().").
Does this mean you'd prefer to have a default and the rule be active from the next release?

2022-10-24 12:17 UTC, paulo-ferraz-oliveira commented
In any case, the only meaningful request to change I see is the fact that the rule should not be restricted to `term()` or `any()`, everything else are details, for me, that I have no strong opinions on:
1. whether the rule is active by default or not (in which case it would need a default),
2. whatever the output message is, as long as it's easy to act on.

I agree with adding more tests.

2022-10-24 12:33 UTC, elbrujohalcon commented on src/elvis_style.erl
> +        "Found usage of type ~p() on line ~p, but your preferred type is ~p().").
I wouldn't add it to the ruleset… but I would have a default value anyway.

2022-10-24 12:36 UTC, elbrujohalcon commented
> 1. whether the rule is active by default or not (in which case it would need a default),
I agree not to activate the rule by default (i.e. not to put it in the default ruleset `erl_files`) but, at the same time, it can totally have a default so users can add it just like…
```erlang
rules => [{elvis_style, whatever_name_it_ends_up_with, #{}}]
```
…without the need to specify a preferred value explicitly.

> 2. whatever the output message is, as long as it's easy to act on.
Yeah… easy to act on is fine, but consistent with other messages is important to me, too.

> I agree with adding more tests.
🤝

2022-10-24 15:08 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +        "Found usage of type ~p() on line ~p, but your preferred type is ~p().").
Make sense. I should've noticed we have that for all rules. I imagine you're referring to activating it without options and letting `elvis_core` do its thing...

2022-10-25 05:46 UTC, elbrujohalcon commented on src/elvis_style.erl
> +        "Found usage of type ~p() on line ~p, but your preferred type is ~p().").
Yeah… Exactly. My goal is for people to be able to _just add the rule_ without explicitly choosing a preferred type. Elvis should not fail in that situation, it should just either consider `term()` or `any()` or `_`… the preferred type.

2022-10-25 05:47 UTC, elbrujohalcon commented
Alright @jackyhui96 … You have green light to move forward with the changes. Sorry again for the back-and-forth.

2022-10-25 09:45 UTC, paulo-ferraz-oliveira commented on doc_rules/elvis_style/types_term_or_any.md
> +  - default: `no_preference`.
I hadn't seen this or other "already resolved" conversations yesterday. GitHub is funny in the way it shows stuff.

2022-10-25 09:47 UTC, paulo-ferraz-oliveira commented on doc_rules/elvis_style/types_term_or_any.md
> +- `preference :: term | any`.
Sure. I guess it would be nice to find time to write down some of these orientations so it's easier to review pull requests (and for people implementing them)... but... time!

2022-10-25 09:49 UTC, paulo-ferraz-oliveira commented
@elbrujohalcon, is the rule to be renamed as `consistent_generic_type`?

2022-10-25 10:02 UTC, paulo-ferraz-oliveira commented
I'm summarising the requested changes below:

- [ ] add a default (named `preferred_type`) to the rule (and update the doc. accordingly): the value is `term`
- [ ] change message to `Found usage of type ~p/0 on line ~p. Please use ~p/0, instead.`
- [ ] add more tests as per https://github.com/inaka/elvis_core/pull/259#pullrequestreview-1152596276
- [ ] doc. should state rule as "Consistent Generic Type": the file should be named `consistent_generic_type.md` and the rule `consistent_generic_type` for use

@elbrujohalcon, let me know if this is it, basically, otherwise I'll update this comment so it's less confusing.

2022-10-25 10:38 UTC, elbrujohalcon commented
comment updated, @paulo-ferraz-oliveira ;)

2022-10-27 06:47 UTC, jackyhui96 commented
Currently it looks like the rule doesn’t apply to callbacks

2022-10-27 07:15 UTC, elbrujohalcon commented
@jackyhui96 you mean that `elvis_code:find/3` doesn't traverse callbacks?
If that's so, it's a bug and it's worth reporting.

2022-10-27 07:20 UTC, elbrujohalcon approved these changes

2022-10-27 07:20 UTC, elbrujohalcon commented
@paulo-ferraz-oliveira I already _approved_ the PR. I leave it up to you to merge it, if you're comfortable with it :)

2022-10-27 07:27 UTC, jackyhui96 commented
> @jackyhui96 you mean that `elvis_code:find/3` doesn't traverse callbacks? If that's so, it's a bug and it's worth reporting it as such.
> 
> Or maybe elements within callbacks are not categorized as types… 🤔 … If that's so, same thing: it merits a bug report.

Yeah it doesn't categorise them as types 😞 this is what the nodes look like for a callback:
```
#{attrs => #{location => {13,1},  text => "-"},           type => '-'},
#{attrs => #{location => {13,2},  text => "callback"},    type => atom, value => callback},
#{attrs => #{location => {13,11}, text => "my_callback"}, type => atom, value => my_callback},
#{attrs => #{location => {13,22}, text => "("},           type => '('},
#{attrs => #{location => {13,23}, text => "term"},        type => atom, value => term},
#{attrs => #{location => {13,27}, text => "("},           type => '('},
#{attrs => #{location => {13,28}, text => ")"},           type => ')'},
#{attrs => #{location => {13,29}, text => ")"},           type => ')'},
#{attrs => #{location => {13,31}, text => "->"},          type => '->'},
#{attrs => #{location => {13,34}, text => "term"},        type => atom, value => term},
#{attrs => #{location => {13,38}, text => "("},           type => '('},
#{attrs => #{location => {13,39}, text => ")"},           type => ')'},
#{attrs => #{location => {13,40}, text => ".\n"},         type => dot},
```

2022-10-27 07:33 UTC, elbrujohalcon commented
Oooooh… that's bad. Do you mind filing a bug for that, @jackyhui96 ?

2022-10-27 07:34 UTC, jackyhui96 commented
@elbrujohalcon sure thing, is this a bug with elvis or with `ktn_code`?

2022-10-27 09:47 UTC, paulo-ferraz-oliveira commented on doc_rules/elvis_style/consistent_generic_type.md
> +- default: `term`.
```suggestion
  - default: `term`.
```

2022-10-27 09:48 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +        "Found usage of type ~p/0 on line ~p. Please use ~p/0, instead.").
@elbrujohalcon, is `/0` really more readable than `()` here? Because the consumer will not find `/0`, but they will find `()`.

2022-10-27 09:51 UTC, paulo-ferraz-oliveira commented
@elbrujohalcon, I left a minor comment (hopefully the last 😄).

2022-10-27 09:55 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +        "Found usage of type ~p/0 on line ~p. Please use ~p/0, instead.").
Solved over Slack... we'll keep as-is.

2022-10-27 09:56 UTC, paulo-ferraz-oliveira commented
@jackyhui96, I'm merging... many thanks for this.

2022-10-27 10:11 UTC, merged