Maintenance updates
inaka/elvis_core pull request #317
Opened 2023-08-06 20:42 UTC by paulo-ferraz-oliveira

This isn't as big as it looks, though there's possibly a lotta changes.

I'll self-review and try to guide you through it to ease the task.

Whenever a change is not super-explicit or supported by the commit message I'll add a comment.

2023-08-06 20:43 UTC, paulo-ferraz-oliveira commented on CONTRIBUTING.md
> +Erlanger Slack channel: [#elvis](https://erlanger.slack.com/archives/C01073W0E15).
I believe this is correct, but lemme know what's the best strategy here.

2023-08-06 20:44 UTC, paulo-ferraz-oliveira commented on README.md
> +[![Erlang Support](https://img.shields.io/badge/Erlang/OTP-24+-blue)](https://www.erlang.org)
Sadly, `ex_doc` seems to choke on this type of stuff

```[ci]: ...```

for example, which is why I adapted stuff a bit.

2023-08-06 20:44 UTC, paulo-ferraz-oliveira commented on rebar.config
Changes best explained in the commit message for 14c58ef.

2023-08-06 20:45 UTC, paulo-ferraz-oliveira commented on src/elvis_core.erl
> +         Results :: [elvis_result:rule() | elvis_result:elvis_error()],
Found by `rebar3 as test test`. Isn't this great?

2023-08-06 20:47 UTC, paulo-ferraz-oliveira commented
I believe you have to change branch protection rules for this
<img width="527" alt="image" src="https://github.com/inaka/elvis_core/assets/7303768/5a108e62-64c9-4bf6-a611-375808e471cc">

2023-08-07 06:54 UTC, elbrujohalcon requested changes

2023-08-07 06:54 UTC, elbrujohalcon commented on CONTRIBUTING.md
> +Erlanger Slack channel: [#elvis](https://erlanger.slack.com/archives/C01073W0E15).
Yeah. It's cool.

2023-08-07 06:54 UTC, elbrujohalcon commented on rebar.config
> +  {rebar3_lint, "~> 3.0.1"},
Does this work? I thought it would not since `rebar3_lint` has this very own app in its deps.

2023-08-07 06:54 UTC, elbrujohalcon commented on rebar.config
> +{alias, [{test, [compile, format, hank, lint, xref, dialyzer, ct, cover, ex_doc]}]}.
Does `lint` work here? Does it use the latest release of this very same project to check this project? I'm not sure if that's a good idea.

2023-08-07 06:54 UTC, elbrujohalcon commented on rebar.config
> +%% == Hank ==
In general, I would recommend to remove all comments from config files. `rebar3_depup` (if we ever end up using it for projects like this one) is not "smart enough" to read comments appropriately and thus it messes them up and places them… somewhere in the file… if at all.

2023-08-07 10:09 UTC, paulo-ferraz-oliveira commented on rebar.config
> +  {rebar3_lint, "~> 3.0.1"},
I'll remove it. `elvis_core` already checks itself 😄

2023-08-07 10:09 UTC, paulo-ferraz-oliveira commented on rebar.config
> +{alias, [{test, [compile, format, hank, lint, xref, dialyzer, ct, cover, ex_doc]}]}.
I'll remove it. `elvis_core` already checks itself 😄

2023-08-07 10:10 UTC, paulo-ferraz-oliveira commented on rebar.config
> +%% == Hank ==
Do you want to do this now? I mean, this seems more like a `depup` limitation than anything else. I haven't looked into `depup` to see how it "reconstructs" the file, but maybe it's similar to what `format` does (?)

2023-08-07 10:15 UTC, paulo-ferraz-oliveira commented on rebar.config
> +{alias, [{test, [compile, format, hank, lint, xref, dialyzer, ct, cover, ex_doc]}]}.
177636c

2023-08-07 10:15 UTC, paulo-ferraz-oliveira commented on rebar.config
> +  {rebar3_lint, "~> 3.0.1"},
177636c

2023-08-07 10:26 UTC, paulo-ferraz-oliveira commented on rebar.config
> +  {rebar3_lint, "~> 3.0.1"},
I also did 0982d97 which achieves what I was going for earlier 😄

2023-08-07 10:26 UTC, paulo-ferraz-oliveira commented on rebar.config
> +{alias, [{test, [compile, format, hank, lint, xref, dialyzer, ct, cover, ex_doc]}]}.
I also did 0982d97 which achieves what I was going for earlier 😄

2023-08-07 10:40 UTC, elbrujohalcon commented on rebar.config
> +%% == Hank ==
It's 100% a limitation of depup… but it's a limitation that will stay there, likely, forever and ever. It's not easy enough to solve to merit spending time in such a _toy_ project. I, its creator, don't take that project seriously so I don't expect anybody else to do so ;)

OTOH… yeah… let's keep the comments if you prefer. Mine was just a _recommendation_ since it seemed like you were adding them now.

2023-08-07 10:43 UTC, paulo-ferraz-oliveira commented on rebar.config
> +%% == Hank ==
There's no other way to "organise" stuff. I do prefer having the comments there, though. One day we'll have `rebar.config` as `mix.exs`: a conventionfull file that's actually compilable (which makes it more interesting for consumption and mostly avoids comments as we know have functions). But when that day came you'd probably not require the parsing/formatting that `depup` uses either, so... 😄

2023-08-07 10:54 UTC, elbrujohalcon approved these changes

2023-08-07 10:54 UTC, merged

2023-08-07 10:55 UTC, elbrujohalcon commented
Feel free to tag a release and publish to hex whenever you want, @paulo-ferraz-oliveira ;)

2023-08-07 10:58 UTC, paulo-ferraz-oliveira commented
Sure. I'll do that now. Thanks.

2023-08-07 11:04 UTC, paulo-ferraz-oliveira commented
Can't!

```
rebar3 hex owner list elvis_core
inaka (inakos@googlegroups.com)
```

2023-08-07 11:05 UTC, paulo-ferraz-oliveira commented
I did the release on GitHub, though 😄, since that one I can.

2023-08-07 11:22 UTC, elbrujohalcon commented
Let me add you as an owner… hold on.

2023-08-07 11:23 UTC, elbrujohalcon commented
Try again

2023-08-07 11:23 UTC, elbrujohalcon commented
Try again, @paulo-ferraz-oliveira

2023-08-07 11:34 UTC, paulo-ferraz-oliveira commented
Yup, that did it. https://hexdocs.pm/elvis_core/readme.html < look at how pretty it looks 😄

2023-08-07 11:49 UTC, elbrujohalcon commented
Beautiful! I wonder… Is there any way to also publish "Rules.md" and its associated folders and files there?

2023-08-07 11:55 UTC, paulo-ferraz-oliveira commented
There is, but we'd have to change all the rules' files, because they mention `.md`, rendered in GitHub (not Hex.pm), not `.html`.

Maybe open an issue and we'll tackle it "in the future" 😄 

At the moment I'm already sad that `hexdocs` version prefix is hard-coded to `v`, which means (below) links to https://github.com/inaka/elvis_core/blob/v3.1.0/README.md#L1 and not https://github.com/inaka/elvis_core/blob/3.1.0/README.md#L1 😭 
<img width="111" alt="image" src="https://github.com/inaka/elvis_core/assets/7303768/b4c34534-f3c9-43ae-96c2-31940c6e0a09">