Add opaque state as a type declaration
inaka/elvis_core pull request #354
Opened 2024-08-16 12:19 UTC by belltoy

Fix #349

2024-08-16 12:41 UTC, elbrujohalcon requested changes
Can you add a test case for this and, if needed, update the corresponding docs?
Thanks.

2024-08-16 12:41 UTC, elbrujohalcon commented on src/elvis_style.erl
> +           TypeOrOpaque and (state == ktn_code:attr(name, Node))
```suggestion
        fun(Node) ->
          ktn_code:attr(name, Node) == state andalso lists:member(ktn_code:type(Node), [type_attr, opaque])
```

2024-08-18 09:48 UTC, belltoy commented
The first implementation was wrong. I've rebased it with some test cases. And also provided cases to verify rule `state_record_and_type` + rule `export_used_types`.

But something looks weird to me. In the [`pass_state_record_and_type.erl`](https://github.com/inaka/elvis_core/blob/main/test/examples/pass_state_record_and_type.erl) case, the type `state()` is defined without exported, but the `state()` is used in the exported function's spec.

2024-08-19 06:20 UTC, elbrujohalcon commented
> But something looks weird to me. In the [`pass_state_record_and_type.erl`](https://github.com/inaka/elvis_core/blob/main/test/examples/pass_state_record_and_type.erl) case, the type `state()` is defined without exported, but the `state()` is used in the exported function's spec.

I'm not 100% sure, but it's likely because we're not running the `used_exported_types` rule on it.

2024-08-19 06:23 UTC, elbrujohalcon approved these changes
I approve the PR, in general.
So, if you don't have time or just don't feel like improving the `gen_server`s, let me know and I'll merge it.
OTOH, if you can improve that code (even when it's _just for tests_), that would be lovely.

2024-08-19 06:23 UTC, elbrujohalcon commented on test/examples/fail_state_record_and_type_plus_export_used_types.erl
> +    ok.
```suggestion
-spec handle_call(term(), term(), state()) -> {noreply, State}.
handle_call(_Request, _From, State) ->
    {noreply, State}.
```

2024-08-19 06:23 UTC, elbrujohalcon commented on test/examples/fail_state_record_and_type_plus_export_used_types.erl
> +    ok.
And the same goes for all other `gen_server` implementations in this PR. Let's make them as _realistic_ as possible.

2024-08-19 06:23 UTC, elbrujohalcon commented on test/examples/fail_state_record_and_type_plus_export_used_types.erl
> +    ok.
You can remote these 3 callbacks, since they are optional and they don't contribute to the validation of the rules we want to enforce here.
The same applies for all the other `gen_server` implementations in this PR.

2024-08-19 06:23 UTC, elbrujohalcon commented on test/examples/fail_state_record_and_type_plus_export_used_types.erl
> +    ok.
I noticed you copied them from `pass_state_record_and_type.erl`, let's take this chance to also simplify that one and make it more _realistic_ 🙏🏻

2024-08-19 06:56 UTC, belltoy commented
Of course, I will improve those codes in test cases.

2024-08-19 08:34 UTC, merged