feat(#297): New rule: Prefer Unquoted Atoms
inaka/elvis_core pull request #355
Opened 2024-09-03 05:52 UTC by bormilan

This is in an early stage, I have som things to fix.

2024-09-03 06:27 UTC, elbrujohalcon requested changes
The code is fine, I would just simplify it by removing the options.

2024-09-03 06:27 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    #{regex => "^'([a-z_0-9)]+)'$", enclosed_atoms => ".*"};
I would not add a `regex` parameter, nor an `enclosed_atoms` one. Those are fine for `atom_naming_convention` since they allow users to decide what atoms to forbid. In this case, the intention of the rule doesn't really allow configuration at all.

2024-09-03 06:27 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    AtomNodes = elvis_code:find(fun is_atom_node/1, Tree, #{traverse => all, mode => node}),
Same as above… I would avoid configuration options entirely.

2024-09-03 06:27 UTC, elbrujohalcon commented on src/elvis_style.erl
> +
Basically… the same as above, again… In my mind the check here should be something like…
```erlang
    AtomName0 = ktn_code:attr(text, AtomNode),
    {IsEnclosed, AtomName} = string_strip_enclosed(AtomName0),
    IsExceptionClass = is_exception_or_non_reversible(ValueAtomName),
    case AtomName of
        [$' | _] when not IsExceptionClass andalso not IsEnclosed ->
%% or… <<$', _/binary>> when not IsExceptionClass andalso not IsEnclosed ->
%% if it's a binary (I don't remember the data type here… sorry)
            Msg = ?ATOM_PREFERRED_QUOTES_MSG,
            {Line, _} = ktn_code:attr(location, AtomNode),
            Info = [AtomName0, Line, RegexEnclosed],
                Result = elvis_result:new(item, Msg, Info, Line),
                AccIn ++ [Result];
        _ ->
            AccIn
    end,
    check_atom_quotes(…).
```

2024-09-03 08:04 UTC, bormilan commented on src/elvis_style.erl
> +    #{regex => "^'([a-z_0-9)]+)'$", enclosed_atoms => ".*"};
I see, I was not sure about them. Thanks for the explanation.

2024-09-03 08:06 UTC, bormilan commented on src/elvis_style.erl
> +
Yes, it's simpler than that, I was thinking about refactoring this, it was a quick solution copying from the `atom_naming_convention`. Thanks!

2024-09-03 20:57 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +         , prefer_unquoted_atoms/3]).
Before submitting, prefer executing `rebar3 test` locally, to have the formatter, linter, etc. do their work 😄

2024-09-03 20:58 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +         , prefer_unquoted_atoms/3]).
(we probably need to update the contributing guide to include this)

2024-09-03 20:59 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +        "but its not needed on it.").
```suggestion
        "Atom ~p on line ~p is quoted "
        "but quotes are not needed.").
```

2024-09-03 21:00 UTC, paulo-ferraz-oliveira commented on test/examples/fail_quoted_atoms.erl
One of the tests should at least contain a few reserved words in quote.

Something like `'maybe'` and `'and'`, for example, for better implementation coverage.

2024-09-04 07:00 UTC, elbrujohalcon commented
Once you're done with the code, @bormilan … you also need to add docs to this rule (in RULES.md) and you need to include it in the appropriate ruleset(s) (I guess `erl_files` and `hrl_files`)

2024-09-04 13:36 UTC, bormilan commented
Thanks for all the help and suggestions, currently I'm on a little vacation, but after that I will fix all of them and update the PR.

2024-09-10 15:29 UTC, bormilan commented on test/examples/fail_quoted_atoms.erl
Do you mean to make exceptions for `'maybe'` and `'and'`? I guess we don't want to use them as `and` because they are keywords.

2024-09-10 15:31 UTC, bormilan commented on src/elvis_style.erl
> +         , prefer_unquoted_atoms/3]).
I'd be happy to do it if you want.

2024-09-10 15:47 UTC, bormilan commented on src/elvis_style.erl
> +    AtomNodes = elvis_code:find(fun is_atom_node/1, Tree, #{traverse => all, mode => node}),
I fixed this, but `rebar3 test` fails on this because it says: 'The following pieces of code are dead and should be removed"
I can't delete them entirely bc all rules function needs to be with arity 3.
Could you help me with this, what do I miss?

2024-09-10 15:59 UTC, bormilan commented on test/examples/fail_quoted_atoms.erl
Oh, I'm so dumb, You can't use a keyword like that, sorry. I never tried so I had not known this.

2024-09-10 16:57 UTC, bormilan commented
Today I made some changes, but I had some questions that I commented on your suggestions above.
Besides these, I have made two hardcoded variables that I want to put somewhere else(bc they are constant values), but I don't know where to. If you could help me with that I would appreciate it. These are `Regex` and `KeyWords`.

2024-09-12 06:59 UTC, elbrujohalcon requested changes
A few improvements and… I wonder what happens with `'maybe'` as an atom.
I checked erlang/otp's code and wherever there is a list of keywords/reserved words… they do **not** include `maybe`, but I guess… if the feature is enabled (and I think it's enabled by default on OTP27+), that one should also be considered _a keyword_, right?

2024-09-12 06:59 UTC, elbrujohalcon commented on doc_rules/elvis_style/prefer_unquoted_atoms.md
> +Do not use quotes on atoms that are not need it.
```suggestion
Do not use quotes on atoms that don't need to be quoted.
```

2024-09-12 06:59 UTC, elbrujohalcon commented on src/elvis_style.erl
> +            {match, _Captured} when not IsException ->
```suggestion
        case unicode:characters_to_list(AtomName, unicode) of
            [$' | _] when not IsException ->
```

We don't need a regex for this, we can just use pattern-matching.

2024-09-12 06:59 UTC, elbrujohalcon commented on src/elvis_style.erl
> +                Info = [AtomName0, Line, RegexEnclosed],
```suggestion
                Info = [AtomName0, Line],
```
The macro has only 2 parameters.

2024-09-12 06:59 UTC, elbrujohalcon commented on test/examples/pass_unquoted_atoms.erl
> +test(_A, _B) -> unquoted_atom.
```suggestion
test(_Reserved, _Words) -> ['after', 'and', 'andalso', 'band', 'begin', 'bnot', 'bor', 'bsl', 'bsr', 'bxor', 'case',
         'catch', 'cond', 'div', 'end', 'fun', 'if', 'let', 'not', 'of', 'or', 'orelse', 'receive',
         'rem', 'try', 'when', 'xor'];
test(_A, _B) -> unquoted_atom.
```

Can we add some reserved words here? Maybe even all of them?

2024-09-12 07:04 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    AtomNodes = elvis_code:find(fun is_atom_node/1, Tree, #{traverse => all, mode => node}),
I'm not sure if that would be _the definitive solution™️ _, but, considering that you're dealing with the text of the file (and not it's AST), it's possible that this rule actually belongs to `elvis_text_style`, instead of `elvis_style`. Hopefully, that will allow you to write more concise functions without the extra arguments.

2024-09-12 12:00 UTC, bormilan commented on doc_rules/elvis_style/prefer_unquoted_atoms.md
> +Do not use quotes on atoms that are not need it.
Sorry for these mistakes.

2024-09-12 12:05 UTC, bormilan commented on src/elvis_style.erl
> +            {match, _Captured} when not IsException ->
Ooh, I see. I did not understand this line first, thank you for the clarification. I like this clean solution, then I can completely get rid of the regex.

2024-09-13 06:28 UTC, elbrujohalcon requested changes
The code is perfectly fine, @bormilan … but I still believe this rule belongs to `elvis_text_style` and not `elvis_style`.

2024-09-16 09:22 UTC, bormilan commented
So, should we add "maybe" to the exceptions? I think we should. But because now it's not a keyword by default, we may wait and add it when erl/OTP27 comes.

2024-09-16 09:41 UTC, elbrujohalcon commented
Personally… I would add it right now… It will be a reserved word soon enough.
I wish Erlang/OTP would have a public function that returned the list of reserved words somewhere (`erl_syntax` may be a great place)… 🤷🏻

2024-09-16 09:42 UTC, elbrujohalcon requested changes

2024-09-16 09:42 UTC, elbrujohalcon commented on RULES.md
> +- [Prefer Unquoted Atoms](doc_rules/elvis_style/prefer_unquoted_atoms.md)
```suggestion
- [Prefer Unquoted Atoms](doc_rules/elvis_text_style/prefer_unquoted_atoms.md)
```

2024-09-16 09:42 UTC, elbrujohalcon commented on doc_rules/elvis_style/prefer_unquoted_atoms.md
> +# Prefer unquoted atoms
This file should be moved to `elvis_text_style` folder.

2024-09-16 09:50 UTC, bormilan commented on RULES.md
> +- [Prefer Unquoted Atoms](doc_rules/elvis_style/prefer_unquoted_atoms.md)
I'm sorry that I forgot this. I will fix it.

2024-09-16 10:08 UTC, elbrujohalcon approved these changes

2024-09-16 10:09 UTC, elbrujohalcon commented
Excellent work, @bormilan !!! Thank you very much!

2024-09-16 10:13 UTC, bormilan commented
Thank you so much for all the help and patience. It was a great start to my journey.

2024-09-16 10:30 UTC, bormilan commented
I found a little problem, the formatter changes the `'maybe'` to `maybe` in the list of exceptions. Should I turn it off to that file, or we should consider changing this in the formatter itself to make an exception for it?

2024-09-16 11:03 UTC, elbrujohalcon commented
@bormilan The list of exceptions should have strings and not atoms… that would fix it :)

2024-09-16 11:04 UTC, elbrujohalcon commented
But… the formatter is broken, anyway… please report an issue there.

2024-09-16 11:33 UTC, elbrujohalcon approved these changes

2024-09-16 14:03 UTC, bormilan commented
> Personally… I would add it right now… It will be a reserved word soon enough. I wish Erlang/OTP would have a public function that returned the list of reserved words somewhere (`erl_syntax` may be a great place)… 🤷🏻

I think `f_reserved_word` does exactly what you want in the module [erl_scan](https://www.erlang.org/docs/17/man/erl_scan)

2024-09-16 14:15 UTC, elbrujohalcon commented
> > Personally… I would add it right now… It will be a reserved word soon enough. I wish Erlang/OTP would have a public function that returned the list of reserved words somewhere (`erl_syntax` may be a great place)… 🤷🏻
> 
> I think `f_reserved_word` does exactly what you want in the module [erl_scan](https://www.erlang.org/docs/17/man/erl_scan)

Yeah, but it's not exported, is it?

2024-09-16 14:16 UTC, merged

2024-09-16 14:18 UTC, bormilan commented
It is:
![image](https://github.com/user-attachments/assets/afbe7794-c0dd-46ac-9c3d-a28d0919e1fa)

2024-09-16 14:18 UTC, bormilan commented
> > > Personally… I would add it right now… It will be a reserved word soon enough. I wish Erlang/OTP would have a public function that returned the list of reserved words somewhere (`erl_syntax` may be a great place)… 🤷🏻
> > 
> > 
> > I think `f_reserved_word` does exactly what you want in the module [erl_scan](https://www.erlang.org/docs/17/man/erl_scan)
> 
> Yeah, but it's not exported, is it?

It is:
![image](https://github.com/user-attachments/assets/afbe7794-c0dd-46ac-9c3d-a28d0919e1fa)

2024-09-16 14:41 UTC, elbrujohalcon commented
> > > > Personally… I would add it right now… It will be a reserved word soon enough. I wish Erlang/OTP would have a public function that returned the list of reserved words somewhere (`erl_syntax` may be a great place)… 🤷🏻
> > > 
> > > 
> > > I think `f_reserved_word` does exactly what you want in the module [erl_scan](https://www.erlang.org/docs/17/man/erl_scan)
> > 
> > 
> > Yeah, but it's not exported, is it?
> 
> It is: ![image](https://private-user-images.githubusercontent.com/71042542/367794513-afbe7794-c0dd-46ac-9c3d-a28d0919e1fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0OTc5NzcsIm5iZiI6MTcyNjQ5NzY3NywicGF0aCI6Ii83MTA0MjU0Mi8zNjc3OTQ1MTMtYWZiZTc3OTQtYzBkZC00NmFjLTljM2QtYTI4ZDA5MTllMWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE0NDExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliM2ZiOGYzZGQ5OTAxY2QzYjQ2NWExZmUyZWM5MGM3ZDM4MjczYmM2MzI2MDIxYTRkOThjZTNhYjU5MjZiODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E6IO_-LNi53DZthdKpUj4E3WKpzYJb2a3oPy7-TTzZ4)

Ah, right! I was thinking of something like `f_reserved_words/0` (that would return the list) :)

2024-09-16 16:34 UTC, bormilan commented
> > > > > Personally… I would add it right now… It will be a reserved word soon enough. I wish Erlang/OTP would have a public function that returned the list of reserved words somewhere (`erl_syntax` may be a great place)… 🤷🏻
> > > > 
> > > > 
> > > > I think `f_reserved_word` does exactly what you want in the module [erl_scan](https://www.erlang.org/docs/17/man/erl_scan)
> > > 
> > > 
> > > Yeah, but it's not exported, is it?
> > 
> > 
> > It is: ![image](https://private-user-images.githubusercontent.com/71042542/367794513-afbe7794-c0dd-46ac-9c3d-a28d0919e1fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0OTc5NzcsIm5iZiI6MTcyNjQ5NzY3NywicGF0aCI6Ii83MTA0MjU0Mi8zNjc3OTQ1MTMtYWZiZTc3OTQtYzBkZC00NmFjLTljM2QtYTI4ZDA5MTllMWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE0NDExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliM2ZiOGYzZGQ5OTAxY2QzYjQ2NWExZmUyZWM5MGM3ZDM4MjczYmM2MzI2MDIxYTRkOThjZTNhYjU5MjZiODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E6IO_-LNi53DZthdKpUj4E3WKpzYJb2a3oPy7-TTzZ4)
> 
> Ah, right! I was thinking of something like `f_reserved_words/0` (that would return the list) :)
> 
> But… maybe we can actually use that here or in `rebar3_format`… 🤔 If you want to send a PR using `erl_scan:f_reserved_word/1` to verify that the atom is actually a reserved word instead of the hardcoded list of strings we now have… I'd merge it, for sure!

Ok, I will do it shortly!