Fix/max function length
inaka/elvis_core pull request #365
Opened 2024-10-01 13:52 UTC by bormilan

# Description

I added a new rule called `max_function_clause_length`.
The old rule `max_function_length` stays the same, it checks the length of an entire function, but now we can check the size of the clauses separately.

Closes #&lt;issue&gt;.

- [ ] I have read and understood the [contributing guidelines](/inaka/elvis_core/blob/main/CONTRIBUTING.md)

2024-10-01 13:58 UTC, bormilan commented
I'm thinking about merging the two rule codes because they are so similar. I should make only one function, that gets parameters(e.g. function or clause), and then call that with the appropriate values.

But on the other hand, I think it's more readable and simple.

What do you think about it?

Oh, and I don't know that the error message is well enough.

2024-10-01 14:30 UTC, elbrujohalcon reviewed
I added some comments regarding the error message.
Personally, I would not merge the functions. In general, issues are usually raised for one particular rule and not for _all the rules that work in the same way_ so (once again: **in general**) it's usually better to keep each rule's logic in its own function, instead of sharing it… But this might be the exception, of course.

2024-10-01 14:30 UTC, elbrujohalcon commented on src/elvis_style.erl
> +        "maximum of ~p.").
```suggestion
        "The code for the clause ~w of function ~p/~w has ~p lines which exceeds the "
        "maximum of ~p.").
```
Or something similar that would point to the actual clause with the issue instead of the whole function.

2024-10-01 14:30 UTC, elbrujohalcon commented on src/elvis_style.erl
> +           Info = [L, MaxLength],
```suggestion
           Info = [ClauseNumber, L, MaxLength],
```
…aaaaand you would need to somehow compute the clause number 😉

2024-10-02 20:23 UTC, paulo-ferraz-oliveira commented on doc_rules/elvis_style/max_function_clause_length.md
> +                                    , count_whitespace => false
```suggestion
                                           , count_comments => false
                                           , count_whitespace => false
```

2024-10-02 20:26 UTC, paulo-ferraz-oliveira commented on src/elvis_rulesets.erl
> +                             max_function_clause_length,
```suggestion
                             max_function_clause_length,
                             max_function_length,
```

2024-10-02 20:26 UTC, paulo-ferraz-oliveira commented on src/elvis_rulesets.erl
> +                             max_function_clause_length,
(to keep it sorted)

2024-10-02 20:29 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +         no_debug_call/3, no_common_caveats_call/3, no_nested_try_catch/3, no_successive_maps/3,
I don't mind the order, here, but preferably changes to existing code bases should touch as little as required. This test could be written (exported) at the end of this "section" and it wouldn't change anything specific, but it would probably change less lines...

2024-10-02 20:33 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +        "maximum of ~p.").
I wouldn't mind having a small translation of

```
1 -> 1st
2 -> 2nd
3 -> 3rd
n -> nth
```

And use that in the message.

Then, as per Brujo's I'd slightly change it to

```diff
-        "The code for clause ~p/~w has ~p lines which exceeds the "
-        "maximum of ~p.").
+        "The code for the ~w clause of function ~p/~w has ~p lines which exceeds the "
+        "maximum of ~p.").

2024-10-02 20:38 UTC, paulo-ferraz-oliveira commented on test/style_SUITE.erl
> +         verify_max_function_length/1, verify_max_function_clause_length/1, verify_no_debug_call/1,
If I understand correctly you put `verify_max_function_clause_length/1` in the middle of existing elements, but the review is a bit harder because of this. No need to change for this pull request. Just food for thought...

2024-10-02 20:40 UTC, paulo-ferraz-oliveira commented
Thanks much. In general, this looks solid. I propose a few tweaks. From my end, I prefer it if you don't resolve the comments while you handle them, since it allows me to check your reply easier (and not having to press "Show resolved" all the time).

2024-10-03 06:34 UTC, bormilan commented on src/elvis_style.erl
> +           Info = [L, MaxLength],
okay, I'm on it :D

2024-10-03 06:34 UTC, elbrujohalcon commented on src/elvis_style.erl
> +         no_debug_call/3, no_common_caveats_call/3, no_nested_try_catch/3, no_successive_maps/3,
Contrary to @paulo-ferraz-oliveira , I do like the fact that the new function was added right after `max_function_length/1`. I guess it's your choice, @bormilan … you get to decide if you want to keep it as-is or move it to the end of the list.

2024-10-03 06:35 UTC, bormilan commented on src/elvis_style.erl
> +        "maximum of ~p.").
It looks nice to me, I'm on it.

2024-10-03 06:39 UTC, elbrujohalcon commented on src/elvis_style.erl
> +        "maximum of ~p.").
In that case, it should be…

```suggestion
        "The code for the ~ts  clause of function ~p/~w has ~p lines which exceeds the "
        "maximum of ~p.").
```

…since "1st"/"2nd"/etc… will definitely be strings.

I don't mind if you implement that translation, @bormilan … but careful that it's 11th/12th/13th and not 11st/12nd/13rd, but it's 21st/22nd/23rd (yeah… functions can have lots of clauses) and not 21th/22th/23th.  This is one of those typicall interview exercises… like translating to/from roman numerals 🤦🏻 .
…and you were wondering when will any of this be useful in real-life™️ , right? 😝

2024-10-03 06:40 UTC, elbrujohalcon commented on src/elvis_style.erl
> +           Info = [L, MaxLength],
You'll need to apply the nth/snd/rd translation here, if you decide to go that way.

2024-10-03 06:42 UTC, elbrujohalcon commented on test/style_SUITE.erl
> +         verify_max_function_length/1, verify_max_function_clause_length/1, verify_no_debug_call/1,
As I stated before, I do appreciate the fact that the new function appears after the existing one for `max_function_length`… and we don't really need to review changes to this list… if a function needs to be exported and it is not, the test will fail anyway ;)

2024-10-03 06:43 UTC, bormilan commented on src/elvis_style.erl
> +        "maximum of ~p.").
Oh okay, it's a little tricky, but I will try to make it as simple as possible.

2024-10-03 06:47 UTC, bormilan commented on src/elvis_style.erl
> +         no_debug_call/3, no_common_caveats_call/3, no_nested_try_catch/3, no_successive_maps/3,
Yes, I like it too, but the other side is understandable too. I think I will leave it here, because it's better to keep them close to each other, in my opinion.

2024-10-03 08:54 UTC, bormilan commented
I'm thinking about that, we should check the error messages during the tests, to make sure we caught the error message we want. 

We should make a function that takes the expected message/messages and returns a boolean based on the result.

If you think it's useful I would be happy to implement it in another issue maybe, or if not I will just write this test by checking the messages by hand.

2024-10-03 10:32 UTC, bormilan commented
I have a short time now, that's why it's half done.

I want to add better test cases, and unit tests for the `case_num` function.

And the "function name" is now bad, so maybe I need to parse the clause_nodes and add the function name and arity to it.

2024-10-03 10:57 UTC, elbrujohalcon commented on src/elvis_style.erl
> +
This function seems too complex and with too many parameters.
I would think this version should work:

```suggestion
%% 11th, 12th, 13th, 111th, …
case_num(X) when X rem 100 >= 11, X rem 100 =< 13 -> integer_to_list(X) ++ "th";
%% 1st, 21st, 101st, …
case_num(X) when X rem 10 == 1 -> integer_to_list(X) ++ "st";
%% 2nd, 22nd, 102nd, …
case_num(X) when X rem 10 == 2 -> integer_to_list(X) ++ "nd";
%% 3rd, 23rd, 103rd, …
case_num(X) when X rem 10 == 3 -> integer_to_list(X) ++ "rd";
%% 4th, 5th, 125th, …
case_num(X) -> integer_to_list(X) ++ "th".
```

This is what I usually expect from interviewees when I present them with the problem. :)

2024-10-03 12:11 UTC, elbrujohalcon commented on src/elvis_style.erl
> +
But you only use `case_num/3` to get the clause number. In fact, shouldn't it be called `clause_num/1`, instead?

2024-10-03 13:08 UTC, bormilan commented
Now, I fixed it a little bit, I hope you find it better too.

2024-10-03 13:10 UTC, elbrujohalcon commented
Sorry, @bormilan … but I still fail to see why you need all the recursiveness in that function. In the end it just needs to return a number in string format, doesn't it?

2024-10-03 13:13 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    integer_to_list(Num) ++ "th".
Wouldn't this return `"11st"` for clause number 11 or 111?
That would be incorrect.

That's why I recommended using:
```erlang
%% 11th, 12th, 13th, 111th, …
case_num(X) when X rem 100 >= 11, X rem 100 =< 13 -> integer_to_list(X) ++ "th";
%% 1st, 21st, 101st, …
case_num(X) when X rem 10 == 1 -> integer_to_list(X) ++ "st";
%% 2nd, 22nd, 102nd, …
case_num(X) when X rem 10 == 2 -> integer_to_list(X) ++ "nd";
%% 3rd, 23rd, 103rd, …
case_num(X) when X rem 10 == 3 -> integer_to_list(X) ++ "rd";
%% 4th, 5th, 125th, …
case_num(X) -> integer_to_list(X) ++ "th".
```

2024-10-03 13:14 UTC, bormilan commented
Do you mean why do I need the function `clause_num` alongside the fun `parse_clause_num`?
Because I need to figure out the clause's number that is not stored in the data of the node, so I need to calculate it by hand. We have a list of all the clauses in the module, so I need to go through them with a `lists:foldl` and calculate the numbers at every node.

2024-10-03 13:18 UTC, bormilan commented on src/elvis_style.erl
> +    integer_to_list(Num) ++ "th".
Oh, you are right, I forgot about 11, 12, 13 ...

2024-10-03 13:23 UTC, bormilan commented
Oh maybe my fault was that I searched all the clauses in the `root`, but I might search for them only in the function node. So I need to search for the functions, and in an inside recursive "iteration" I run through the clauses. This way I will end up with a two-deep algorithm, but I don't need to calculate the clause numbers like I did.

2024-10-03 13:35 UTC, bormilan commented
This solution would be good in my opinion, but because the fact that I need the function name and arity too, I need to switch to the two-deep solution. When I started this looked better because of simplicity, but I was wrong now I see. (sad)

2024-10-05 07:51 UTC, bormilan commented
Now I made the new version, with this I don't need that plus function for the clause numbers. I made a new test, and before merging, I want to make an assertion about the messages(to prove that clause numbers and the message itself are correct) if you think it's good too.

(and of course, I will delete the comments)

2024-10-07 06:32 UTC, elbrujohalcon approved these changes

2024-10-07 06:36 UTC, elbrujohalcon commented
I'm approving. I think this is mergeable as it is, but if you feel like adding a test for the clause numbers, running elvis on a file like this should produce one error per clause.

```erlang
-module( … ).

-elvis([{max_length_function_clause, #{max_length => 0}}]).

-export([clause/1]).

clause(1) -> "1st";
clause(2) -> "2nd";
…
clause(111) -> "111th";
clause(112) -> "112th";
clause(113) -> "113th";
–
clause(125) -> "125th".
```

2024-10-07 14:05 UTC, elbrujohalcon approved these changes
I like it. I'll defer final approval to @paulo-ferraz-oliveira … but everything looks good from my perspective.

2024-10-07 14:12 UTC, bormilan commented
Thank you so much!

2024-10-08 20:53 UTC, paulo-ferraz-oliveira commented
I tweaked the PR title since this'll go directly into the generated release Changelog.

2024-10-08 20:54 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +        "maximum of ~p.").
If it becomes too convoluted just go with clause #...

2024-10-08 20:55 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +         no_debug_call/3, no_common_caveats_call/3, no_nested_try_catch/3, no_successive_maps/3,
Which is why I prefer a single function per line, in any case... easier to sort, easier to walk through.

2024-10-08 20:56 UTC, paulo-ferraz-oliveira commented on test/style_SUITE.erl
> +         verify_max_function_length/1, verify_max_function_clause_length/1, verify_no_debug_call/1,
I wouldn't mind the order if they were sorted already. They're not 😄

2024-10-08 20:57 UTC, paulo-ferraz-oliveira approved these changes
I'm Ok, I guess, but I don't know what changed since my last review, since all the commits were squashed.

2024-10-08 20:58 UTC, paulo-ferraz-oliveira commented on doc_rules/elvis_style/max_function_clause_length.md
> +  - default: `30`.
```suggestion
- `max_length :: non_neg_integer()`
  - default: `30`
```

2024-10-08 20:58 UTC, paulo-ferraz-oliveira commented on Untitled
Is this on purpose? I'd remove it otherwise...

2024-10-08 20:59 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +        "The code for the ~ts  clause of function ~p/~w has ~p lines which exceeds the "
```suggestion
        "The code for the ~ts clause of function ~p/~w has ~p lines which exceeds the "
```

2024-10-08 21:01 UTC, paulo-ferraz-oliveira commented
I left a couple of comments above, that should be handled; after that we're good to go. Thanks.

2024-10-10 12:09 UTC, bormilan commented
> I'm Ok, I guess, but I don't know what changed since my last review, since all the commits were squashed.

Oh, sorry next time I will wait with it till the very end.

2024-10-12 21:20 UTC, paulo-ferraz-oliveira commented on Untitled
Is this file (named `Untitled` with content `tyl`) added on purpose? Or can it be removed?

2024-10-13 08:57 UTC, bormilan commented on Untitled
Sorry, I removed it. I don't know how I missed that when I committed my changes.

2024-10-13 11:30 UTC, elbrujohalcon requested changes

2024-10-13 11:30 UTC, elbrujohalcon commented on test/style_SUITE.erl
> +             "33rd"].
This won't test anything… for this to assert something, you should use…
```suggestion
    Numbers = ["1st",
             "5th",
             "6th",
             "7th",
             "11th",
             "13th",
             "19th",
             "20th",
             "21st",
             "29th",
             "30th",
             "31st",
             "33rd"].
```

2024-10-13 11:30 UTC, elbrujohalcon commented on test/style_SUITE.erl
> +             "33rd"].
But, while that would work, in correct CT _verbiage_, the right way of write an assertion is…
```suggestion
    ["1st",
             "5th",
             "6th",
             "7th",
             "11th",
             "13th",
             "19th",
             "20th",
             "21st",
             "29th",
             "30th",
             "31st",
             "33rd"] = Numbers.
```

(i.e., with the expected value to the left)

2024-10-13 11:30 UTC, elbrujohalcon commented
Almost there, @bormilan

2024-10-13 14:45 UTC, bormilan commented on test/style_SUITE.erl
> +             "33rd"].
Oh, you're right. Always the expected on the left.

2024-10-16 06:10 UTC, elbrujohalcon approved these changes

2024-10-16 06:12 UTC, elbrujohalcon commented
Thanks, @bormilan !!! Amazing work.

2024-10-16 06:12 UTC, merged