No init lists
inaka/elvis_core pull request #367
Opened 2024-10-07 15:43 UTC by bormilan

# Description

A brief description of your changes.

Closes #329;.

- [ ] I have read and understood the [contributing guidelines](/inaka/elvis_core/blob/main/CONTRIBUTING.md)

2024-10-07 16:04 UTC, bormilan commented
Do we want to check that the module implements a `gen_*` behavior, or should we check every module like now?

2024-10-07 16:17 UTC, elbrujohalcon requested changes
This needs more tests, specifically:
* A module that implements `gen_server` or `gen_statem` and…
  - has `init([_|_]) -> …`: Should fail.
  - has `init(A = [1,2,3]) -> …`: Should fail
  - has `init/1` implemented with multiple clauses, all of them expecting a list: Should fail.
  - has `init/1` implemented with multiple clauses, one of them not being a list: Should **pass**, even if other clauses expect a list.
  - has `init/1` implemented using a map, but `init/2` implemented using a list in one of the arguments: Should **pass**.
  - has `init/0` implemented using a tuple, but also `init/0`: Should **pass**.
* A module that doesn't implement a behaviour and has `init([1,2,3]) -> …`: Should **pass**.

2024-10-07 16:17 UTC, elbrujohalcon commented on RULES.md
> +- [Not Use List In Init Functions](doc_rules/elvis_style/no_init_lists.md)
```suggestion
- [No Init Lists](doc_rules/elvis_style/no_init_lists.md)
```

It's better if the name of the rule matches with the md file… and it's also the title there, so… everything matches :)

2024-10-07 16:17 UTC, elbrujohalcon commented on doc_rules/elvis_style/no_init_lists.md
> +[Reasoning](https://erlangforums.com/t/args-in-gen-init-1/3169/4?u=elbrujohalcon)
```suggestion
Do not use a list as the parameter for the `init/1` callback when implementing `gen_*` behaviours. It's semantically clearer to use a tuple or a map. [More info](https://erlangforums.com/t/args-in-gen-init-1/3169/4?u=elbrujohalcon).
```

2024-10-07 16:17 UTC, elbrujohalcon commented on doc_rules/elvis_style/no_init_lists.md
> +the files are pre-processed)
```suggestion
> Works on `.beam` files? Yes!
```

2024-10-07 16:17 UTC, elbrujohalcon commented on src/elvis_style.erl
> +        "Don't use a list as a parameter in 'init' function at position ~p.").
```suggestion
        "Do not use a list as the parameter for the 'init' callback at position ~p.").
```

2024-10-07 16:17 UTC, elbrujohalcon commented on test/examples/fail_verify_no_init_lists.erl
> +init([_AParam]) ->
This file should actually _work_… It should not fail since it's not implementing any behaviour.
If the file is not implementing a behaviour that requires an `init/1` callback, we don't care how `init/1` is implemented.

2024-10-08 20:48 UTC, paulo-ferraz-oliveira commented on doc_rules/elvis_style/no_init_lists.md
> +[Reasoning](https://erlangforums.com/t/args-in-gen-init-1/3169/4?u=elbrujohalcon)
I think it's safe to remove `?u=elbrujohalcon` from the link.

2024-10-08 20:50 UTC, paulo-ferraz-oliveira commented on test/examples/fail_verify_no_init_lists.erl
> +init([_AParam]) ->
Agreed, to start we should just go with a few hard-coded Erlang behaviours; then we can extend as time goes by (they don't come by that often, in any case).

2024-10-08 20:51 UTC, paulo-ferraz-oliveira reviewed
You're on the right path here ❤️ Just a few more tweaks...

2024-10-08 20:53 UTC, paulo-ferraz-oliveira commented
I tweaked the PR title since this'll go directly into the generated release Changelog.

2024-10-10 12:25 UTC, bormilan commented
Thanks for the comments, I will solve all of them if I have some time. <3

2024-10-10 12:53 UTC, bormilan commented on doc_rules/elvis_style/no_init_lists.md
> +[Reasoning](https://erlangforums.com/t/args-in-gen-init-1/3169/4?u=elbrujohalcon)
You are right I removed and changed the last id from `4` to `5` to point the link to the right comment.

2024-10-10 13:39 UTC, elbrujohalcon requested changes
Still missing some changes, but I just wanted to add feedback about the recent additions.

2024-10-10 13:39 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    Root = get_root(#{}, Target, #{}),
```suggestion
no_init_lists(Config, Target, RuleConfig) ->
    Root = get_root(Config, Target, RuleConfig),
```

Did you need to use empty maps there for a reason, @bormilan ?

2024-10-10 13:39 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    FilterFun = fun({Name, _, C}) -> length(C) > 0 andalso Name =:= init end,
I'm not sure but… if `C` is the list of arguments… the it has to be **exactly** 1.
```suggestion
    FilterFun = fun({Name, _, Args}) -> length(Args) =:= 1 andalso Name =:= init end,
```

2024-10-10 13:41 UTC, bormilan commented on src/elvis_style.erl
> +    FilterFun = fun({Name, _, C}) -> length(C) > 0 andalso Name =:= init end,
Yes, you are right it's a dumb fault.

2024-10-10 13:47 UTC, bormilan commented on src/elvis_style.erl
> +    Root = get_root(#{}, Target, #{}),
Yes, you are right again, I just left it in...

2024-10-15 19:12 UTC, bormilan commented
I still have some work to do, but it keeps getting better.

2024-10-16 06:13 UTC, elbrujohalcon commented
@bormilan do you mind merging `main` into your branch, please?

2024-10-16 06:25 UTC, elbrujohalcon requested changes
A few small suggestions, but overall great progress @bormilan 👍🏻

2024-10-16 06:25 UTC, elbrujohalcon commented on src/elvis_style.erl
> +-feature(maybe_expr, enable).
I don't think you need this anymore, do you?

2024-10-16 06:25 UTC, elbrujohalcon commented on src/elvis_style.erl
> +-feature(maybe_expr, enable).
Actually… this is a great idea for a Hank rule: _Unused features_ 🤔

2024-10-16 06:25 UTC, elbrujohalcon commented on src/elvis_style.erl
> +-feature(maybe_expr, enable).
https://github.com/AdRoll/rebar3_hank/issues/221

2024-10-16 06:25 UTC, elbrujohalcon commented on src/elvis_style.erl
> +%         "Do not use a list as the parameter for the 'init' callback at position ~p.").
I'm gonna guess we'll need this macro before merging the PR, right?

2024-10-16 06:25 UTC, elbrujohalcon commented on src/elvis_style.erl
> +            end;
```suggestion
            lists:member(ktn_code:attr(value, BehaviourNode), Behaviors)
```

2024-10-16 06:25 UTC, elbrujohalcon commented on test/examples/no_init_lists_examples/pass_no_init_lists2.erl
> +  gen_server:start_link(?MODULE, undefined, []).
```suggestion
  gen_server:start_link(?MODULE, #{a => map}, []).
```
Subtle and pointless, but just for consistency (i.e., to match what `init/1` expects).

2024-10-16 06:25 UTC, elbrujohalcon commented on test/examples/no_init_lists_examples/pass_no_init_lists3.erl
> +  gen_server:start_link(?MODULE, undefined, []).
```suggestion
  gen_server:start_link(?MODULE, {1, 2}, []).
```
Subtle and pointless, but just for consistency (i.e., to match what `init/1` expects).

2024-10-16 06:25 UTC, elbrujohalcon commented on test/examples/no_init_lists_examples/pass_no_init_lists.erl
> +  gen_server:start_link(?MODULE, undefined, []).
```suggestion
  gen_server:start_link(?MODULE, 1, []).
```
Subtle and pointless, but just for consistency (i.e., to match what `init/1` expects).

2024-10-16 08:34 UTC, bormilan commented on src/elvis_style.erl
> +            end;
Oh...
🤦‍♂️

2024-10-16 08:36 UTC, bormilan commented on src/elvis_style.erl
> +%         "Do not use a list as the parameter for the 'init' callback at position ~p.").
Yes, I commented it out because I just experienced a weird bug that said it's not used. (But I clearly used it) I will investigate it, this is a temporary solution.

2024-10-18 11:43 UTC, elbrujohalcon commented on src/elvis_style.erl
> +                lists:filter(FilterFun, FunListAttributeInfos);
```suggestion
                [Location || {init, Location, [_]} <- FunListAttributeInfos];
```
You can use list comprehensions to filter… and, since you only need the location later, you can just retrieve that.

2024-10-18 11:43 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    lists:map(ResultFun, FunListAttributes).
If you follow my suggestion above, you can simplify this…
```suggestion
    ResultFun =
        fun(Location) ->
           Info = [Location],
           Msg = ?NO_INIT_LISTS_MSG,
           elvis_result:new(item, Msg, Info, Location)
        end,
    lists:map(ResultFun, FunListAttributes).
```

2024-10-18 11:43 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    lists:map(ResultFun, FunListAttributes).
You can (probably… I had not tested it) simplify this multi-loop algorithm on a single list comprehension…
```suggestion
    case is_rule_behaviour(Root, RuleConfig) of
        true ->
            IsInit =
                fun(Node) ->
                    ktn_code:type == function
                    andalso ktn_code:attr(name, FunctionNode) == init
                end,
            InitFunctions = elvis_code:find(IsInit, Root),
            [ elvis:result:new(
                item,
                ?NO_INIT_LISTS_MSG,
                [ktn_code:attr(location, FunctionNode)],
                ktn_code:attr(location, FunctionNode))
            || FunctionNode <- InitFunctions, 
                Content <- ktn_code:content(FunctionNode),
                length(ktn_code:node_attr(pattern, Content)) == 1, %% We only care about init/1
                Attr <- ktn_code:node_attr(pattern, Content),
                cons == ktn_code:type(Attr) %% We only raise warnings if the pattern is a list
            ];
        false ->
            []
    end.
```

2024-10-18 11:43 UTC, elbrujohalcon commented on src/elvis_style.erl
> +is_rule_behaviour(Root, RuleConfig) ->
Renaming suggestion: `is_relevant_behaviour` or `is_important_behaviour` or `is_known_behaviour`.
`is_rule_behaviour`, to me, sounds like if it's looking for `-behaviour(rule).`

2024-10-18 11:45 UTC, elbrujohalcon requested changes
One more test (or maybe, two), @bormilan:

* A module that implements `gen_server` AND another behaviour…

```erlang
-module(fail…).

-behaviour(gen_server).
-behaviour(another_behaviour).

-export([init/1]).

init([]) -> {error, "should not be a list"}.
```

2024-10-18 11:48 UTC, bormilan commented
> One more test (or maybe two, if you want a fail and a pass), @bormilan:
> 
> * A module that implements `gen_server` AND another behaviour…
> 
> ```erlang
> -module(fail…).
> 
> -behaviour(gen_server).
> -behaviour(another_behaviour).
> 
> -export([init/1]).
> 
> init([]) -> {error, "should not be a list"}.
> ```

Yes! I like making more and more tests to feel that my code is 100% good.

2024-10-18 11:55 UTC, elbrujohalcon commented
> Yes! I like making more and more tests to feel that my code is 100% good.

HA! I just saw that you were matching against a single `[BehaviourNode]` in your code… and I wondered "what would happen if we have multiple ones?"… so… we have to test that, right?

2024-10-18 11:59 UTC, bormilan commented
> > Yes! I like making more and more tests to feel that my code is 100% good.
> 
> HA! I just saw that you were matching against a single `[BehaviourNode]` in your code… and I wondered "what would happen if we have multiple ones?"… so… we have to test that, right?

You're right. I'm working on the new logic right now, so it's the perfect time to add new tests and consider all the possible barriers.

2024-10-18 15:31 UTC, bormilan commented on src/elvis_style.erl
> +    lists:map(ResultFun, FunListAttributes).
Oh, I was so engrossed in work that I had not checked your comments and I reworked all this... (And I didn't get notifications, which is weird)

2024-10-18 15:31 UTC, bormilan commented on src/elvis_style.erl
> +is_rule_behaviour(Root, RuleConfig) ->
Good idea, thanks

2024-10-18 15:38 UTC, bormilan commented on src/elvis_style.erl
> +    lists:map(ResultFun, FunListAttributes).
But I think I can make something like this in my new code too.

2024-10-18 15:41 UTC, bormilan commented
The only test that is not working now is the one with the `init([])` because its attribute type is `nil`. I don't know how I will solve this, it may need some extra magic. Or is it a bug in `katana_code`?

2024-10-19 08:38 UTC, elbrujohalcon commented
> The only test that is not working now is the one with the `init([])` because its attribute type is `nil`. I don't know how I will solve this, it may need some extra magic. Or is it a bug in `katana_code`?

Isn't it as simple as `lists:member(ktn_code:type(Attr), [cons, nil])`?

I think `nil` is precisely `[]`, which is fine.

2024-10-19 08:48 UTC, elbrujohalcon requested changes

2024-10-19 08:48 UTC, elbrujohalcon commented on src/elvis_style.erl
> +                IsFunction = fun(Node) -> ktn_code:type(Node) == function end,
I still think it would be better to filter out more functions here…
```suggestion
                IsFunction = fun(Node) -> ktn_code:type(Node) == function andalso ktn_code:attr(name, Node) == init end,
```
…even more… if we can only keep the ones that have a single argument through this filter, that would simplify the remaining part of this function code much more.

2024-10-19 08:48 UTC, elbrujohalcon commented on src/elvis_style.erl
> +                     length(lists:filter(fun(Elem) -> is_list_node(Elem) end, Attributes)) =:= 1
This would be true for a function like `init([_], second_argument) -> …` (it has 1 list argument) and that function does **not** break the rule.

2024-10-19 08:48 UTC, elbrujohalcon commented on src/elvis_style.erl
> +                     length(lists:filter(fun(Elem) -> is_list_node(Elem) end, Attributes)) =:= 1
Please add a test for that.

2024-10-19 09:07 UTC, bormilan commented on src/elvis_style.erl
> +                     length(lists:filter(fun(Elem) -> is_list_node(Elem) end, Attributes)) =:= 1
Okay, thanks for the feedback!

2024-10-19 09:08 UTC, bormilan commented
> precisely

Oh! Okay, that's nice, I started to dig into the code of katana, thanks for the clarification.

2024-10-19 09:09 UTC, bormilan commented
> > The only test that is not working now is the one with the `init([])` because its attribute type is `nil`. I don't know how I will solve this, it may need some extra magic. Or is it a bug in `katana_code`?
> 
> Isn't it as simple as `lists:member(ktn_code:type(Attr), [cons, nil])`?
> 
> I think `nil` is precisely `[]`, which is fine.

Oh! Okay, that's nice, I started to dig into the code of katana, thanks for the clarification.

2024-10-19 09:09 UTC, bormilan commented on src/elvis_style.erl
> +                IsFunction = fun(Node) -> ktn_code:type(Node) == function end,
Oh yes, thanks!

2024-10-24 10:00 UTC, bormilan commented on src/elvis_style.erl
> +                IsFunction = fun(Node) -> ktn_code:type(Node) == function end,
If I have a full understanding, you say this because we don't want to really know what the args of `init/2` are, because `gen_server` needs `init/1` at every case, and we only want to check that if `init/1` expects a list as its parameter.

So we don't care if `init/2` expects a list at any of its parameters, because if `init/1` expects a map we will pass it.
And we don't care if `init/2` expects two non-list parameters, because if `init/1` expects a list we will fail.

Am I right on that, or do you think something else?

2024-10-24 10:41 UTC, elbrujohalcon commented on src/elvis_style.erl
> +                IsFunction = fun(Node) -> ktn_code:type(Node) == function end,
Exactly! All OTP behaviours expect a single argument in `init(…)`. That's what kickstarted this whole thing. `gen_server` docs use a list as _InitArgs_… while in reality it's just a single _InitArg_ that doesn't need to be a list at all.
That's what confuses devs (particularly, newcommers) about this thing.

2024-10-24 10:50 UTC, bormilan commented on src/elvis_style.erl
> +                IsFunction = fun(Node) -> ktn_code:type(Node) == function end,
Ohhh I see. Now it's finally clear, it's nice that I started working on this so I could learn this :D

2024-10-24 13:20 UTC, elbrujohalcon requested changes
We're almost there, @bormilan … really really close to the final version.

2024-10-24 13:20 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    #{behaviours => [gen_server, gen_statem]};
```suggestion
    #{behaviours => [gen_server, gen_statem, gen_fsm, supervisor, supervisor_bridge, gen_event]};
```

Let's add the other ones that I found while grepping for `-callback init` in OTP's codebase :)

2024-10-24 13:20 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    #{behaviours => [gen_server, gen_statem]};
If you add a simple test for each one of them… like the module below… much better. If not, no big deal.

```erlang
-module(fail_{BEHAVIOUR}).

-behaviour({BEHAVIOUR}).

-export([init/1]).

init([]) -> {error, "Don't use lists for init/1"}.
```

(Replacing `{BEHAVIOUR}` with the name of each behaviour, obviously).

2024-10-24 14:25 UTC, bormilan commented on src/elvis_style.erl
> +                [Init1Fun] = elvis_code:find(IsInit1Function, Root),
umm, I'm trying but the compilation fails if there are some undefined callback functions.

2024-10-24 14:25 UTC, bormilan commented on src/elvis_style.erl
> +    #{behaviours => [gen_server, gen_statem]};
yes, I'm going to add all of them.

2024-10-24 14:33 UTC, elbrujohalcon commented on src/elvis_style.erl
> +                [Init1Fun] = elvis_code:find(IsInit1Function, Root),
So the compiler compiles all the modules that we use for testing? I was not aware of that. In any case, you can add a `-compile(…).` attribute to the module to avoid warnings. I'll see if I can find the right value to put there.

2024-10-24 14:37 UTC, elbrujohalcon commented on src/elvis_style.erl
> +                [Init1Fun] = elvis_code:find(IsInit1Function, Root),
I added the module (granted: I didn't add no test for it) locally and it seems to compile just fine. What error are you seeing?

2024-10-24 15:04 UTC, bormilan commented on src/elvis_style.erl
> +                [Init1Fun] = elvis_code:find(IsInit1Function, Root),
I see, something like this: -compile([{nowarn_unused_function}]).

2024-10-24 15:34 UTC, elbrujohalcon commented on src/elvis_style.erl
> +                [Init1Fun] = elvis_code:find(IsInit1Function, Root),
Well… it seems like there is no way to bypass the behaviour check in the Erlang compiler, so… Do not add such a test, but do fix the code to account for `elvis_code:find(…)` returning `[]` here.

2024-10-24 15:39 UTC, elbrujohalcon commented on src/elvis_style.erl
> +                [Init1Fun] = elvis_code:find(IsInit1Function, Root),
Drop a note like this one when you do it…
```erlang
case elvis_code:find(IsInit1Function, Root) of
    [] ->
        %% A module that implements the behaviour without defining init/1 is valid
        %% but adding it to our tests will prevent us from compiling the project.
        %% That's why this part of the code will remain not covered by tests.
        [];
    [Init1Fun] ->
        …
```

2024-10-24 15:41 UTC, bormilan commented on src/elvis_style.erl
> +                [Init1Fun] = elvis_code:find(IsInit1Function, Root),
Okay, I will make it! Thank you for the help!

2024-10-24 15:48 UTC, elbrujohalcon commented on src/elvis_style.erl
> +                [Init1Fun] = elvis_code:find(IsInit1Function, Root),
https://github.com/erlang/otp/issues/8985

2024-10-24 16:16 UTC, elbrujohalcon requested changes

2024-10-24 16:16 UTC, elbrujohalcon commented on src/elvis_style.erl
> +                    end,
This won't work, @bormilan … `Init1Fun` being `[]` will only cause errors down the line. I'll make a code suggestion that's more likely to work in this case…

2024-10-24 16:16 UTC, elbrujohalcon commented on src/elvis_style.erl
> +        end,
```suggestion
    ListInitClauses =
        case is_relevant_behaviour(Root, RuleConfig) of
            true ->
                IsInit1Function =
                    fun(Node) ->
                       ktn_code:type(Node) == function
                       andalso ktn_code:attr(name, Node) == init
                       andalso ktn_code:attr(arity, Node) == 1
                    end,

                case elvis_code:find(IsInit1Function, Root) of
                    [] ->
                        [];
                    [Init1Fun] ->
                        FilterClauses =
                            fun(Clause) ->
                                [Attribute] = ktn_code:node_attr(pattern, Clause),
                                case is_list_node(Attribute) of
                                    true ->
                                        {true, ktn_code:attr(location, Clause)};
                                    false ->
                                        false
                                end
                            end,

                        Content = ktn_code:content(Init1Fun),
                        ListAttrClauses = lists:filtermap(FilterClauses, Content),
                        case length(ListAttrClauses) =:= length(Content) of
                            true ->
                                ListAttrClauses;
                            false ->
                                []
                        end;
                end;
            false ->
                []
        end,
```

2024-10-24 16:16 UTC, elbrujohalcon commented on src/elvis_style.erl
> +        end,
Something like this ☝🏻 should work

2024-10-24 17:10 UTC, bormilan commented on src/elvis_style.erl
> +                    end,
yes, I just wrote this without thinking. The problem was exactly this even at the beginning of this fix.. 😅

2024-10-26 09:28 UTC, elbrujohalcon requested changes
Excellent job, @bormilan !! Only one more change.

2024-10-26 09:28 UTC, elbrujohalcon commented on Untitled
> +
Is this file needed?

2024-10-27 06:33 UTC, bormilan commented on Untitled
> +
I'm sorry about that. I have two computers, and they have different nvim setups, so I usually mess up with the shortcuts. 😅

2024-10-27 06:52 UTC, elbrujohalcon approved these changes

2024-10-27 06:52 UTC, merged

2025-05-22 23:13 UTC, paulo-ferraz-oliveira commented
Too bad we can't silence this (by default) if the function it detects the issue in has spec `-> supervisor:child_spec().` because as-is we're going "against" OTP documentation: not sure we have an issue to propose a change there... 🤔

2025-05-23 06:59 UTC, elbrujohalcon commented
@paulo-ferraz-oliveira do you have an example of that? Because `child_spec/0` should define the parameters you would pass to `your_module:start_link/#`, not the ones you pass to `gen_something:start_link/#`, AFAIR.

2025-05-25 11:48 UTC, paulo-ferraz-oliveira commented
Yeah, so I did it in a hurry, and clearly `{M, F, {}}` is wrong, since it should be `{M, F, [{}]}`, but this is again something that might be confusing to first-time users. It is what it is, though.

2025-05-25 11:51 UTC, paulo-ferraz-oliveira commented
Fwiw, here's the correct example

```erlang
child_spec() ->
  #{
    id => mylib,
    start => {mylib, start_link, [_StartLinkArgs = {}]}
  }.

start_link(StartLinkArgs) ->
  gen_server:start_link(?MODULE, _InitArgs = {}, []).

init(InitArgs) ->
  {ok, state}. % state, in this case, is "whatever".
```