fix(no_successive_maps): prevent failing on nested maps
inaka/elvis_core pull request #372
Opened 2024-11-10 09:57 UTC by bormilan

# Description

I just added the option: `traverse => all` to the rule because when I investigated the problem with the provided example, I realized that the `elvis_code:find` does not go deep into this nested map, because the zippers can go deeper only if a `node` is a `branch`.  A node is identified as a `branch` if it has something in its `content` field(if the traverse is set to `content`). So we need to change `traverse` to `all` so the `elvis_code` can use the `node_attrs` as the children of the node.

In this example, the rule fails because a `map_field_assoc` type node contains no content, preventing the function `elvis_code:find` from going deeper; it only returns that one map.

Closes #339.

- [ ] I have read and understood the [contributing guidelines](/inaka/elvis_core/blob/main/CONTRIBUTING.md)

2024-11-10 11:13 UTC, paulo-ferraz-oliveira approved these changes
Looks Ok to me. Thanks.

2024-11-11 07:22 UTC, elbrujohalcon requested changes
I don't understand how you made tests pass on OTP27, but the rest of the PR is cool.

2024-11-11 07:22 UTC, elbrujohalcon commented on test/examples/fail_no_successive_maps2.erl
> +    #{}.
How does this fail in OTP27? 🤔 
The other branch of the `-if(…). … -else. …` does emit a warning.

2024-11-11 07:22 UTC, elbrujohalcon approved these changes

2024-11-11 07:22 UTC, merged

2024-11-11 07:23 UTC, elbrujohalcon commented on test/examples/fail_no_successive_maps2.erl
> +    #{}.
Oh, I see… elvis ignores the macros… HAHAHA!
It's a clever trick… but maybe in the future, we should add a comment so it doesn't surprise future us :P