Ets fun2ms without ms transform
inaka/elvis_core pull request #374
Opened 2024-11-15 17:52 UTC by bormilan

# Description

It detects if a module that does not include `ms_transform.hrl` has any `ets:fun2ms` function call.

Closes #313;

- [x] I have read and understood the [contributing guidelines](/inaka/elvis_core/blob/main/CONTRIBUTING.md)

2024-11-17 09:27 UTC, elbrujohalcon requested changes
For performance (and semantics) sake, I would do the check in the opposite direction. In other words, instead of first looking for all files that don't include ms_transform and checking each one to see if they use ets:fun2ms… I would look for all files that use ets:fun2ms (which are surely far less than the ones that don't include ms_transform) and then check if they include the hrl or not.

You should also add a test with a file that has the `-include` but not the usage of `fun2ms`, for completeness sake. Like…

```erlang
-module(pass_ms_transform_included_too).

-include_lib("stdlib/include/ms_transform.hrl").

-export([test/0]).

test() -> ok.
```

2024-11-17 09:27 UTC, elbrujohalcon commented on src/elvis_style.erl
> +        "Missing inclide library: stdlib/include/ms_transform.hrl at position ~p.").
```suggestion
        "Missing inclide library: stdlib/include/ms_transform.hrl when ets:fun2ms/1 is used at position ~p.").
```

2024-11-17 10:18 UTC, bormilan commented
Oh yes, that is a way better approach. Thanks!

2024-11-17 21:42 UTC, bormilan commented
I made some changes based on your suggestions. However, I believe this rule could be more generic. Currently, it only checks for a specific scenario, but we can expand it. 

We could create a rule that detects any function call that requires an include but does not have it. We can add this scenario to the default configuration, and users can also add their own pairs of `{function_call, lib_file_name}` if they wish.

2024-11-18 07:17 UTC, elbrujohalcon requested changes
A few tiny improvements in code and docs… and do consider adding the tests I requested in my previous review, @bormilan.
Thanks.

2024-11-18 07:17 UTC, elbrujohalcon commented on doc_rules/elvis_style/ms_transform_included.md
> +# No Init Lists
```suggestion
# Include `ms_transform` for `ets:fun2ms/1`
```

2024-11-18 07:17 UTC, elbrujohalcon commented on src/elvis_style.erl
> +           end
```suggestion
           case ktn_code:type(Node) of
               call ->
                   is_ets_fun2ms(Node);
               _ ->
                   false
           end
```
Or…
```suggestion
           ktn_code:type(Node) == call andalso is_ets_fun2ms(Node)
```

2024-11-18 07:17 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    {ets, fun2ms} == {ktn_code:attr(value, Module), ktn_code:attr(value, Fun2)}.
```suggestion
    ets == ktn_code:attr(value, Module) andalso fun2ms == ktn_code:attr(value, Fun2).
```
To avoid computing a thing if the other is not the one we're expecting it to be (i.e., short-circuiting).

2024-11-18 07:17 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    end.
```suggestion
    [] /= elvis_code:find(Fun, Root).
```

At least in theory… you can include that file twice. I'm not sure if that code would compile but, as long as it's included **at least once**, it should be fine for our rule.

2024-11-18 07:17 UTC, elbrujohalcon commented on src/elvis_style.erl
> +    end.
Maybe try adding a test like…
```erlang
-module(pass_ms_transform_included_twice).

-include_lib("stdlib/include/ms_transform.hrl").
-include_lib("stdlib/include/ms_transform.hrl").

-export([test/0]).

test() -> ets:fun2ms(fun(_) -> ok end).
```

2024-11-18 07:18 UTC, bormilan commented
Okay, it sounds

> A few tiny improvements in code and docs… and do consider adding the tests I requested in my previous review, @bormilan. Thanks.

Yes, I will add that test, I didn't forget.

2024-11-18 07:22 UTC, bormilan commented on src/elvis_style.erl
> +    {ets, fun2ms} == {ktn_code:attr(value, Module), ktn_code:attr(value, Fun2)}.
Oh, its smart, thanks!

2024-11-18 07:24 UTC, bormilan commented on src/elvis_style.erl
> +           end
Yes, I was confused about a lot of cases 😅
Your second one is so clean, thanks!

2024-11-18 07:26 UTC, bormilan commented on src/elvis_style.erl
> +    end.
Oh yeah, this simple assertion is much better.
I will add this test too, thanks!

2024-11-20 20:12 UTC, elbrujohalcon approved these changes
A little bit of nit-picking, but overall the code is great.
If you feel like ignoring the nit-picky comments, @bormilan … just let me know and I'll merge the PR as-is.

2024-11-20 20:12 UTC, elbrujohalcon commented on src/elvis_style.erl
> +        end,
```suggestion
    IsIncluded = FunctionCalls /= [] andalso is_include_ms_transform(Root),
```

2024-11-20 20:12 UTC, elbrujohalcon commented on src/elvis_style.erl
> +is_include_ms_transform(Root) ->
I would call this function `has_include_for_ms_transform/1`, because we're looking for an include, we're not checking if the node _is_ the include itself.

2024-11-20 20:32 UTC, bormilan commented
> If you feel like ignoring the nit-picky comments, @bormilan … just let me know and I'll merge the PR as-is.

No, I'm grateful for your time, and I want to bring home as much as I can from these, so please be as nit-picky as you want, I really appreciate it! 🙌

Some say, "God is in the details."
I want to appreciate this project with the best work I can do for the opportunities it provides me on my journey.

2024-11-21 08:09 UTC, elbrujohalcon requested changes

2024-11-21 08:09 UTC, elbrujohalcon commented on test/examples/used_ignored_variable_in_macro.erl
> +-module(used_ignored_variable_in_macro).
I don't think this file belongs to this PR.

2024-11-21 17:57 UTC, elbrujohalcon approved these changes

2024-11-21 17:58 UTC, merged

2024-11-23 11:41 UTC, paulo-ferraz-oliveira commented on src/elvis_rulesets.erl
> +               ms_transform_included,
@elbrujohalcon, I wonder if, in the future, to ease maintenance, this list should be build like a sub-set of `_strict`, for example...