add forbidden regex
inaka/elvis_core pull request #377
Opened 2024-12-01 15:05 UTC by bormilan

# Description

I added the `forbidden_regex' to all "naming_convention" rules.
I made tests for a simple case about making numbers forbidden.

I can't decide in these situations that making a "case in case" is a good implementation. I feel that moving these into another function is not much cleaner, and maybe reading is more frustrating if you need to look into another function just for another case. What do you think about it?

Closes #151.

- [x] I have read and understood the [contributing guidelines](/inaka/elvis_core/blob/main/CONTRIBUTING.md)

2024-12-01 21:04 UTC, elbrujohalcon requested changes

2024-12-01 21:04 UTC, elbrujohalcon commented on src/elvis_style.erl
> +        "The function ~p does written in a forbidden format"
_is written_, not _does written_.
And the same applies to the other texts.

2024-12-01 21:25 UTC, bormilan commented on doc_rules/elvis_style/atom_naming_convention.md
> +by a different configuration option (use `same` if you want the same value as `regex`).
I don't really understand this, what do you mean?

2024-12-02 06:37 UTC, elbrujohalcon commented on doc_rules/elvis_style/atom_naming_convention.md
> +by a different configuration option (use `same` if you want the same value as `regex`).
we have a regex for accepted atom names (i.e., `regex`), but we also have a regex for enclosed atoms (i.e., `enclosed_atoms`). Now we added `forbidden_regex` that limits what's accepted by `regex`. Should it also limit what's accepted by `enclosed_atoms` or not?
I would say "no" and I would add another property, called `forbidden_enclosed_atoms` to deal with what's forbidden in enclosed atoms.

2024-12-05 13:42 UTC, elbrujohalcon requested changes

2024-12-05 13:42 UTC, elbrujohalcon commented on doc_rules/elvis_style/atom_naming_convention.md
> +For enclosed atoms we defined a different forbidden regex, called `forbidden_enclosed_regex`.
```suggestion
To define forbidden enclosed atoms (like the ones in `forbidden_regex` apply for `regex`), use `forbidden_enclosed_regex`.
```

2024-12-05 13:42 UTC, elbrujohalcon commented on doc_rules/elvis_style/atom_naming_convention.md
> +- `forbidden_enclosed_regex :: string() | undefined`.
According to the description above this field **and also `enclosed_atoms`** should also support the atom `same` and then use the same value as the corresponding parameter for non-enclosed atoms.
If that works, we should have tests for it.

2024-12-05 13:42 UTC, elbrujohalcon commented on src/elvis_style.erl
> +                            Regex),
```suggestion
                            ForbiddenRegex),
```
Careful… if `Regex` is the default for `RegexEnclosed`, `ForbiddenRegex` should be the default for `ForbiddenEnclosedRegex`. Since the tests didn't fail with `Regex` here, that means we need more tests to prove that this works as expected.

2024-12-05 15:15 UTC, bormilan commented on src/elvis_style.erl
> +                            Regex),
That's right; I was inattentive about this one.

2024-12-05 15:15 UTC, bormilan commented on doc_rules/elvis_style/atom_naming_convention.md
> +- `forbidden_enclosed_regex :: string() | undefined`.
yes, I fix it.

2024-12-05 15:40 UTC, elbrujohalcon requested changes

2024-12-05 15:40 UTC, elbrujohalcon commented on doc_rules/elvis_style/atom_naming_convention.md
> +- `forbidden_enclosed_regex :: string() | undefined`.
I mean… it should say `string() | undefined | same` here and there.

2024-12-05 15:40 UTC, elbrujohalcon commented on src/elvis_style.erl
> +            end
```suggestion
            case ForbiddenRegex of
                undefined -> errors_for_function_names(Regex, ForbiddenRegex, RemainingFuncNames);
                ForbiddenRegex ->
                    case re:run(FunctionNameStr, ForbiddenRegex, [unicode]) of
                {match, _} ->
                    Msg = ?FORBIDDEN_FUNCTION_NAMING_CONVENTION_MSG,
                    Info = [FunctionNameStr, Regex],
                    Result = elvis_result:new(item, Msg, Info, 1),
                    [Result | errors_for_function_names(Regex, ForbiddenRegex, RemainingFuncNames)];
                nomatch ->
                    errors_for_function_names(Regex, ForbiddenRegex, RemainingFuncNames)
                 end
            end
```

I see what you did there… and… it's clever, but we don't abuse `andalso` in this project (¬_¬)

I think.

2024-12-05 15:40 UTC, elbrujohalcon commented on src/elvis_style.erl
> +                    case ForbiddenRegex =/= undefined
Same as above, please don't abuse the poor short-circuit operator.

2024-12-05 15:40 UTC, elbrujohalcon commented on src/elvis_style.erl
> +                case ForbiddenRegex =/= undefined
Same as all the other places before.

2024-12-05 15:40 UTC, elbrujohalcon commented on src/elvis_style.erl
> +            case ForbiddenRegex =/= undefined
…aaaand another one.

2024-12-05 17:44 UTC, elbrujohalcon approved these changes

2024-12-05 17:48 UTC, elbrujohalcon commented
> But what's the problem with `andalso`? or why do we want to avoid it?

The _implicit_ specification for `andalso` (giving its _desired_ semantics) is `boolean() andalso boolean() -> boolean()`, but the actual way in which `andalso` work is (as you noticed in your code) `boolean() andalso Type -> Type`. In other words, while it's _semantically_ expected for the second expression to be boolean… it works anyway if it's not because that's how the VM optimizes this code.

Taking advantage of an optimization to mess up with the expected semantics of an expression is _not a great thing to do_. First of all, nothing prevents the OTP team from changing that behaviour in the future and crash if the second part is not a boolean. But more importantly… for developers reading that code… finding something that's not a boolean there is unexpected and _surprising future devs_ is not usually a good thing in terms of maintainability.

2024-12-05 17:49 UTC, elbrujohalcon commented
I'll leave the PR open for another day so @paulo-ferraz-oliveira can review… and if he doesn't request changes by then, I'll merge it.

2024-12-05 21:27 UTC, paulo-ferraz-oliveira commented on doc_rules/elvis_style/atom_naming_convention.md
> +Except if it matches with a defined `forbidden_regex`.
```suggestion
All atoms should be named according to the provided regular expression,
except if they match with a defined `forbidden_regex`.
```

2024-12-05 21:28 UTC, paulo-ferraz-oliveira commented on doc_rules/elvis_style/function_naming_convention.md
> +Except if it matches with a defined `forbidden_regex`.
```suggestion
All functions should be named according to the provided regular expression,
except if they match with a defined `forbidden_regex`.
```

2024-12-05 21:28 UTC, paulo-ferraz-oliveira commented on doc_rules/elvis_style/module_naming_convention.md
> +Except if it matches with a defined `forbidden_regex`.
```suggestion
All modules should be named according to the provided regular expression,
except if they match with a defined `forbidden_regex`.
```

2024-12-05 21:29 UTC, paulo-ferraz-oliveira commented on doc_rules/elvis_style/variable_naming_convention.md
> +Except if it matches with a defined `forbidden_regex`.
```suggestion
All variables should be named according to the provided regular expression,
except if they match with a defined `forbidden_regex`.
```

2024-12-05 21:31 UTC, paulo-ferraz-oliveira commented on src/elvis_style.erl
> +        "defined by the regular expression '~p'.").
All of these should refer "name" instead of format, because function format is odd to read. I'll probably not be able to comment on the other warnings because they're outside the scope of the pull request, but you could change them all to e.g. "Function ~p's name does not...", "Variable ~p's name, on line ~p, does not...", etc.

2024-12-05 21:32 UTC, paulo-ferraz-oliveira commented on test/style_SUITE.erl
> +    [_, _, _] =
It would be nice to have the line numbers here, even if that means that changing the files the tests would fail, because it's easier to review.

2024-12-05 21:34 UTC, paulo-ferraz-oliveira commented on test/style_SUITE.erl
> +                              #{regex => "^[a-z](_?[a-z0-9]+)*$", forbidden_regex => "[0-9]"},
You could/should be building these from a call to the function that defines them (`default`), otherwise it makes for more complex maintenance.

2024-12-05 21:34 UTC, paulo-ferraz-oliveira approved these changes
Generally approving, but did comment on a few things that could be improved.

2024-12-06 15:53 UTC, bormilan commented
> > But what's the problem with `andalso`? or why do we want to avoid it?
> 
> The _implicit_ specification for `andalso` (giving its _desired_ semantics) is `boolean() andalso boolean() -> boolean()`, but the actual way in which `andalso` works is (as you noticed in your code) `boolean() andalso Type -> Type`. In other words, while it's _semantically_ expected for the second expression to be boolean… it works anyway if it's not because that's how the VM optimizes this code.
> 
> Taking advantage of an optimization to mess up with the expected semantics of an expression is _not a great thing to do_. First of all, nothing prevents the OTP team from changing that behaviour in the future and crash if the second part is not a boolean (that would be semantically correct, anyway). But more importantly… for developers reading that code… finding something that's not a boolean there is unexpected and _surprising future devs_ is not usually a good thing in terms of maintainability.

Thank you for this explanation. I truly appreciate these "small" things that I can't learn anywhere else. Thanks again for the effort you put into these reviews!

2024-12-07 09:58 UTC, paulo-ferraz-oliveira commented
@bormilan, it's also one of the reasons behind https://github.com/inaka/elvis_core/blob/main/doc_rules/elvis_style/no_block_expressions.md. I was seeing (and writing, since Erlang didn't forbid me) code like:

```erlang
Connected andalso begin
  NumberOfEvents = num_events(...)
  NumberOfEvents > 10 orelse log(...)
end
```

While that works, it's generally messy to maintain.

2024-12-09 14:50 UTC, bormilan commented
> @bormilan, it's also one of the reasons behind https://github.com/inaka/elvis_core/blob/main/doc_rules/elvis_style/no_block_expressions.md. I was seeing (and writing, since Erlang didn't forbid me) code like:
> 
> ```erlang
> Connected andalso begin
>   NumberOfEvents = num_events(...)
>   NumberOfEvents > 10 orelse log(...)
> end
> ```
> 
> While that works, it's generally messy to maintain.

Thank you for the hint and all the reviews, too!

2024-12-09 14:52 UTC, bormilan commented on test/style_SUITE.erl
> +                              #{regex => "^[a-z](_?[a-z0-9]+)*$", forbidden_regex => "[0-9]"},
I see, you are right.

2024-12-09 15:10 UTC, bormilan commented on test/style_SUITE.erl
> +    [_, _, _] =
Yes, you are right, but this rule does not return the line number, only the name of the function and the `regex`.
Now it works like this:
```erlang
            Info = [FunctionNameStr, Regex],
            Result = elvis_result:new(item, Msg, Info, 1),
```
So the number `1` is hardcoded to every Result fun, and we do not add it to the `Info` list.

2024-12-09 15:58 UTC, elbrujohalcon approved these changes

2024-12-14 12:55 UTC, bormilan commented
If it's okay, I will rebase it to prepare for the merge.

2024-12-16 07:47 UTC, elbrujohalcon commented
We can just _squash and merge_, no need for rebasing.

2024-12-16 07:47 UTC, merged